import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';
import XLSX from 'xlsx';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

// Columnas del contrato unificado (backend InventarioExcelService.COLUMNAS_EXCEL, plantilla v2.1.0).
// El orden importa: el backend lee la fila por posicion y rechaza cualquier cabecera que no
// calce exactamente con esta lista (InventarioExcelService.validarEncabezados).
const VERSION_PLANTILLA = '2.1.0';

const HEADERS = [
  'nombre_publicado',
  'categoria',
  'subcategoria',
  'marca_repuesto',
  'sku_proveedor',
  'referencia_oem',
  'tipo_precio',
  'precio',
  'stock',
  'condicion',
  'compatibilidad_general',
  'compatibilidad_marca',
  'compatibilidad_modelo',
  'anio_desde',
  'anio_hasta',
  'motor',
  'descripcion',
  'requiere_chasis'
];

const COMPAT_HEADERS = [
  'sku_proveedor',
  'compatibilidad_marca',
  'compatibilidad_modelo',
  'anio_desde',
  'anio_hasta',
  'motor',
  // 2.1.0: el OEM vive por compatibilidad, igual que en la carga 1 a 1.
  'referencia_oem'
];

function r(data) {
  return {
    nombre_publicado: data.nombre_publicado || '',
    categoria: data.categoria || '',
    subcategoria: data.subcategoria || '',
    marca_repuesto: data.marca_repuesto || '',
    sku_proveedor: data.sku_proveedor || '',
    referencia_oem: data.referencia_oem || '',
    tipo_precio: data.tipo_precio || 'MOSTRAR_PRECIO',
    precio: data.precio !== undefined ? data.precio : '',
    stock: data.stock !== undefined ? data.stock : 10,
    condicion: data.condicion || 'ORIGINAL',
    compatibilidad_general: data.compatibilidad_general || '',
    compatibilidad_marca: data.compatibilidad_marca || '',
    compatibilidad_modelo: data.compatibilidad_modelo || '',
    anio_desde: data.anio_desde || '',
    anio_hasta: data.anio_hasta || '',
    motor: data.motor || '',
    descripcion: data.descripcion || '',
    requiere_chasis: data.requiere_chasis || 'NO'
  };
}

// 120 Productos detallados y realistas con taxonomía canónica
const productos = [
  // --- FRENOS (1-10) ---
  r({
    sku_proveedor: 'REP-001',
    nombre_publicado: 'Pastillas de Freno Delanteras Cerámicas Brembo',
    categoria: 'Frenos',
    subcategoria: 'Pastillas de Freno',
    marca_repuesto: 'Brembo',
    referencia_oem: '04465-02220',
    tipo_precio: 'MOSTRAR_PRECIO',
    precio: 34990,
    stock: 25,
    condicion: 'ORIGINAL',
    compatibilidad_marca: 'Toyota',
    compatibilidad_modelo: 'Corolla',
    anio_desde: 2014,
    anio_hasta: 2019,
    motor: '1.8 16V',
    descripcion: 'Juego de 4 pastillas delanteras de compuesto cerámico de alto rendimiento con placas anti-ruido.',
    requiere_chasis: 'NO'
  }),
  r({
    sku_proveedor: 'REP-002',
    nombre_publicado: 'Disco de Freno Delantero Ventilado Bosch 275mm',
    categoria: 'Frenos',
    subcategoria: 'Discos',
    marca_repuesto: 'Bosch',
    referencia_oem: '43512-0D060',
    tipo_precio: 'MOSTRAR_PRECIO',
    precio: 42900,
    stock: 16,
    condicion: 'ORIGINAL',
    compatibilidad_marca: 'Toyota',
    compatibilidad_modelo: 'Yaris',
    anio_desde: 2016,
    anio_hasta: 2021,
    motor: '1.5 16V',
    descripcion: 'Disco de freno ventilado con recubrimiento anticorrosivo de alta disipación térmica.',
    requiere_chasis: 'NO'
  }),
  r({
    sku_proveedor: 'REP-003',
    nombre_publicado: 'Caliper de Freno Delantero Izquierdo TRW',
    categoria: 'Frenos',
    subcategoria: 'Caliper',
    marca_repuesto: 'TRW',
    referencia_oem: '58110-1R000',
    tipo_precio: 'MOSTRAR_PRECIO',
    precio: 68500,
    stock: 6,
    condicion: 'ALTERNATIVO',
    compatibilidad_marca: 'Hyundai',
    compatibilidad_modelo: 'Accent',
    anio_desde: 2012,
    anio_hasta: 2022,
    motor: '1.4 / 1.6',
    descripcion: 'Pinza / caliper de freno hidráulico ensamblado con pistón y retenes de alta durabilidad.',
    requiere_chasis: 'SI'
  }),
  r({
    sku_proveedor: 'REP-004',
    nombre_publicado: 'Bomba Principal de Freno con Depósito Ferodo',
    categoria: 'Frenos',
    subcategoria: 'Bomba de Freno',
    marca_repuesto: 'Ferodo',
    referencia_oem: '46010-1HM0A',
    tipo_precio: 'MOSTRAR_PRECIO',
    precio: 52000,
    stock: 8,
    condicion: 'ORIGINAL',
    compatibilidad_marca: 'Nissan',
    compatibilidad_modelo: 'Versa',
    anio_desde: 2013,
    anio_hasta: 2019,
    motor: '1.6 16V',
    descripcion: 'Cilindro maestro de freno doble circuito con sensor de nivel de líquido incorporado.',
    requiere_chasis: 'NO'
  }),
  r({
    sku_proveedor: 'REP-005',
    nombre_publicado: 'Kit de Patines de Freno Trasero Ferodo',
    categoria: 'Frenos',
    subcategoria: 'Patines de Freno',
    marca_repuesto: 'Ferodo',
    referencia_oem: '53200-68L00',
    tipo_precio: 'MOSTRAR_PRECIO',
    precio: 22990,
    stock: 20,
    condicion: 'ALTERNATIVO',
    compatibilidad_marca: 'Suzuki',
    compatibilidad_modelo: 'Swift',
    anio_desde: 2012,
    anio_hasta: 2017,
    motor: '1.2 / 1.4',
    descripcion: 'Juego de zapatas / patines para frenos de tambor trasero con forro vulcanizado.',
    requiere_chasis: 'NO'
  }),
  r({
    sku_proveedor: 'REP-006',
    nombre_publicado: 'Tambor de Freno Trasero 200mm Brembo',
    categoria: 'Frenos',
    subcategoria: 'Tambores',
    marca_repuesto: 'Brembo',
    referencia_oem: '93740251',
    tipo_precio: 'MOSTRAR_PRECIO',
    precio: 36500,
    stock: 12,
    condicion: 'ORIGINAL',
    compatibilidad_marca: 'Chevrolet',
    compatibilidad_modelo: 'Sail',
    anio_desde: 2011,
    anio_hasta: 2017,
    motor: '1.4',
    descripcion: 'Tambor de freno rectificado y balanceado para eje trasero con fijación de 4 pernos.',
    requiere_chasis: 'NO'
  }),
  r({
    sku_proveedor: 'REP-007',
    nombre_publicado: 'Cilindro Auxiliar de Freno Trasero TRW',
    categoria: 'Frenos',
    subcategoria: 'Cilindro de Freno',
    marca_repuesto: 'TRW',
    referencia_oem: '58311-02000',
    tipo_precio: 'MOSTRAR_PRECIO',
    precio: 14990,
    stock: 30,
    condicion: 'ORIGINAL',
    compatibilidad_marca: 'Kia',
    compatibilidad_modelo: 'Morning',
    anio_desde: 2011,
    anio_hasta: 2016,
    motor: '1.0 / 1.2',
    descripcion: 'Bombín de freno de rueda trasera en aleación de aluminio resistente a la corrosión.',
    requiere_chasis: 'NO'
  }),
  r({
    sku_proveedor: 'REP-008',
    nombre_publicado: 'Servo Freno Asistido por Vacío Bosch',
    categoria: 'Frenos',
    subcategoria: 'Servo Freno',
    marca_repuesto: 'Bosch',
    referencia_oem: '1K1614106J',
    tipo_precio: 'SOLO_COTIZAR',
    precio: 145000,
    stock: 4,
    condicion: 'ORIGINAL',
    compatibilidad_marca: 'Volkswagen',
    compatibilidad_modelo: 'Golf',
    anio_desde: 2014,
    anio_hasta: 2020,
    motor: '1.4 TSI',
    descripcion: 'Servofreno reforzado de doble diafragma para sistema de asistencia de frenado.',
    requiere_chasis: 'SI'
  }),
  r({
    sku_proveedor: 'REP-009',
    nombre_publicado: 'Piola de Freno de Mano Trasera Derecha Valeo',
    categoria: 'Frenos',
    subcategoria: 'Piola Freno de Mano',
    marca_repuesto: 'Valeo',
    referencia_oem: '4745W1',
    tipo_precio: 'MOSTRAR_PRECIO',
    precio: 18900,
    stock: 14,
    condicion: 'ALTERNATIVO',
    compatibilidad_marca: 'Peugeot',
    compatibilidad_modelo: '208',
    anio_desde: 2013,
    anio_hasta: 2019,
    motor: '1.2 PureTech / 1.6 HDi',
    descripcion: 'Cable de accionamiento de freno de estacionamiento con recubrimiento de polímero.',
    requiere_chasis: 'NO'
  }),
  r({
    sku_proveedor: 'REP-010',
    nombre_publicado: 'Interruptor Switch de Pedal de Freno Bosch',
    categoria: 'Frenos',
    subcategoria: 'Switch de Freno',
    marca_repuesto: 'Bosch',
    referencia_oem: '93810-3K000',
    tipo_precio: 'MOSTRAR_PRECIO',
    precio: 11990,
    stock: 35,
    condicion: 'ORIGINAL',
    compatibilidad_marca: 'Hyundai',
    compatibilidad_modelo: 'Tucson',
    anio_desde: 2016,
    anio_hasta: 2021,
    motor: '2.0 CRDi / 2.0 MPI',
    descripcion: 'Sensor / switch de luz de freno y desactivación de control crucero de 4 pines.',
    requiere_chasis: 'NO'
  }),

  // --- FILTROS (11-18) ---
  r({
    sku_proveedor: 'REP-011',
    nombre_publicado: 'Filtro de Aceite Blindado Mann-Filter W 68/3',
    categoria: 'Filtros',
    subcategoria: 'Filtro de Aceite',
    marca_repuesto: 'Mann-Filter',
    referencia_oem: '90915-10003',
    tipo_precio: 'MOSTRAR_PRECIO',
    precio: 6990,
    stock: 60,
    condicion: 'ORIGINAL',
    compatibilidad_marca: 'Toyota',
    compatibilidad_modelo: 'Yaris',
    anio_desde: 2014,
    anio_hasta: 2022,
    motor: '1.3 / 1.5',
    descripcion: 'Filtro de aceite roscado con válvula anti-retorno y medio filtrante sintético.',
    requiere_chasis: 'NO'
  }),
  r({
    sku_proveedor: 'REP-012',
    nombre_publicado: 'Filtro de Aire Motor Panel Mann-Filter C 25 040',
    categoria: 'Filtros',
    subcategoria: 'Filtro de Aire',
    marca_repuesto: 'Mann-Filter',
    referencia_oem: '17801-21050',
    tipo_precio: 'MOSTRAR_PRECIO',
    precio: 12500,
    stock: 45,
    condicion: 'ORIGINAL',
    compatibilidad_marca: 'Toyota',
    compatibilidad_modelo: 'Corolla',
    anio_desde: 2015,
    anio_hasta: 2020,
    motor: '1.8 Dual VVT-i',
    descripcion: 'Filtro de admisión de aire plisado con sello de poliuretano de alta retención de polvo.',
    requiere_chasis: 'NO'
  }),
  r({
    sku_proveedor: 'REP-013',
    nombre_publicado: 'Filtro de Combustible Diésel Mann-Filter WK 820/17',
    categoria: 'Filtros',
    subcategoria: 'Filtro de Combustible',
    marca_repuesto: 'Mann-Filter',
    referencia_oem: '23390-0L050',
    tipo_precio: 'MOSTRAR_PRECIO',
    precio: 21990,
    stock: 28,
    condicion: 'ORIGINAL',
    compatibilidad_marca: 'Toyota',
    compatibilidad_modelo: 'Hilux',
    anio_desde: 2016,
    anio_hasta: 2022,
    motor: '2.4 / 2.8 D-4D',
    descripcion: 'Filtro de petróleo con trampa de agua y sensor de drenaje para motores common rail.',
    requiere_chasis: 'NO'
  }),
  r({
    sku_proveedor: 'REP-014',
    nombre_publicado: 'Filtro de Cabina / Polen con Carbón Activo Bosch',
    categoria: 'Filtros',
    subcategoria: 'Filtro de Polen',
    marca_repuesto: 'Bosch',
    referencia_oem: '97133-2E210',
    tipo_precio: 'MOSTRAR_PRECIO',
    precio: 13900,
    stock: 35,
    condicion: 'ORIGINAL',
    compatibilidad_marca: 'Hyundai',
    compatibilidad_modelo: 'Tucson',
    anio_desde: 2016,
    anio_hasta: 2021,
    motor: '2.0',
    descripcion: 'Filtro purificador de aire de cabina que elimina polen, olores y partículas finas PM2.5.',
    requiere_chasis: 'NO'
  }),
  r({
    sku_proveedor: 'REP-015',
    nombre_publicado: 'Filtro de Aceite Ecológico Mahle OX 188D',
    categoria: 'Filtros',
    subcategoria: 'Filtro de Aceite',
    marca_repuesto: 'Mahle',
    referencia_oem: '04152-YZZA6',
    tipo_precio: 'MOSTRAR_PRECIO',
    precio: 7490,
    stock: 50,
    condicion: 'ORIGINAL',
    compatibilidad_marca: 'Toyota',
    compatibilidad_modelo: 'RAV4',
    anio_desde: 2013,
    anio_hasta: 2019,
    motor: '2.0 / 2.5',
    descripcion: 'Elemento filtrante de celulosa con sellos O-ring de goma para carcasa de plástico.',
    requiere_chasis: 'NO'
  }),
  r({
    sku_proveedor: 'REP-016',
    nombre_publicado: 'Filtro de Combustible en Línea Gasolina Bosch',
    categoria: 'Filtros',
    subcategoria: 'Filtro de Combustible',
    marca_repuesto: 'Bosch',
    referencia_oem: '16400-00QAA',
    tipo_precio: 'MOSTRAR_PRECIO',
    precio: 10990,
    stock: 32,
    condicion: 'ALTERNATIVO',
    compatibilidad_marca: 'Nissan',
    compatibilidad_modelo: 'Sentra',
    anio_desde: 2014,
    anio_hasta: 2019,
    motor: '1.8',
    descripcion: 'Filtro metálico para línea de inyección de combustible a alta presión.',
    requiere_chasis: 'NO'
  }),
  r({
    sku_proveedor: 'REP-017',
    nombre_publicado: 'Filtro de Aire Alto Flujo Mann-Filter C 35 154',
    categoria: 'Filtros',
    subcategoria: 'Filtro de Aire',
    marca_repuesto: 'Mann-Filter',
    referencia_oem: '1K0129620D',
    tipo_precio: 'MOSTRAR_PRECIO',
    precio: 15990,
    stock: 22,
    condicion: 'ORIGINAL',
    compatibilidad_marca: 'Volkswagen',
    compatibilidad_modelo: 'Golf',
    anio_desde: 2014,
    anio_hasta: 2020,
    motor: '1.4 TSI / 2.0 GTI',
    descripcion: 'Filtro cilíndrico de aire para motores turboalimentados con excelente flujo.',
    requiere_chasis: 'NO'
  }),
  r({
    sku_proveedor: 'REP-018',
    nombre_publicado: 'Filtro de Cabina Antibacteriano Mahle LAK 855',
    categoria: 'Filtros',
    subcategoria: 'Filtro de Polen',
    marca_repuesto: 'Mahle',
    referencia_oem: 'KD45-61-J6X',
    tipo_precio: 'MOSTRAR_PRECIO',
    precio: 16900,
    stock: 18,
    condicion: 'ORIGINAL',
    compatibilidad_marca: 'Mazda',
    compatibilidad_modelo: 'CX-5',
    anio_desde: 2017,
    anio_hasta: 2023,
    motor: '2.0 / 2.5 SkyActiv',
    descripcion: 'Filtro de habitáculo antialérgico con recubrimiento de polifenoles naturales.',
    requiere_chasis: 'NO'
  }),

  // --- SUSPENSIÓN (19-28) ---
  r({
    sku_proveedor: 'REP-019',
    nombre_publicado: 'Amortiguador Delantero a Gas Excel-G KYB 333383',
    categoria: 'Suspensión',
    subcategoria: 'Amortiguadores',
    marca_repuesto: 'KYB',
    referencia_oem: '48510-52H40',
    tipo_precio: 'MOSTRAR_PRECIO',
    precio: 54900,
    stock: 14,
    condicion: 'ORIGINAL',
    compatibilidad_marca: 'Toyota',
    compatibilidad_modelo: 'Yaris',
    anio_desde: 2016,
    anio_hasta: 2021,
    motor: '1.5',
    descripcion: 'Puntal de amortiguación hidráulico presurizado con gas nitrógeno bitubo.',
    requiere_chasis: 'NO'
  }),
  r({
    sku_proveedor: 'REP-020',
    nombre_publicado: 'Amortiguador Trasero Monroe OESpectrum',
    categoria: 'Suspensión',
    subcategoria: 'Amortiguadores',
    marca_repuesto: 'Monroe',
    referencia_oem: '55300-1R000',
    tipo_precio: 'MOSTRAR_PRECIO',
    precio: 38900,
    stock: 18,
    condicion: 'ORIGINAL',
    compatibilidad_marca: 'Hyundai',
    compatibilidad_modelo: 'Accent',
    anio_desde: 2012,
    anio_hasta: 2022,
    motor: '1.4 / 1.6',
    descripcion: 'Amortiguador monotubo trasero para máximo confort y estabilidad direccional.',
    requiere_chasis: 'NO'
  }),
  r({
    sku_proveedor: 'REP-021',
    nombre_publicado: 'Bandeja de Suspensión Delantera Derecha con Rótula TRW',
    categoria: 'Suspensión',
    subcategoria: 'Bandejas',
    marca_repuesto: 'TRW',
    referencia_oem: '54500-1HK0A',
    tipo_precio: 'MOSTRAR_PRECIO',
    precio: 49990,
    stock: 10,
    condicion: 'ALTERNATIVO',
    compatibilidad_marca: 'Nissan',
    compatibilidad_modelo: 'Versa',
    anio_desde: 2013,
    anio_hasta: 2019,
    motor: '1.6',
    descripcion: 'Brazo oscilante inferior de suspensión con bujes de goma y rótula pre-instalados.',
    requiere_chasis: 'NO'
  }),
  r({
    sku_proveedor: 'REP-022',
    nombre_publicado: 'Bieleta Barra Estabilizadora Delantera TRW',
    categoria: 'Suspensión',
    subcategoria: 'Bieletas',
    marca_repuesto: 'TRW',
    referencia_oem: '48820-0D080',
    tipo_precio: 'MOSTRAR_PRECIO',
    precio: 14500,
    stock: 40,
    condicion: 'ORIGINAL',
    compatibilidad_marca: 'Toyota',
    compatibilidad_modelo: 'Corolla',
    anio_desde: 2014,
    anio_hasta: 2019,
    motor: '1.8',
    descripcion: 'Tirante de conexión estabilizadora con juntas esféricas reforzadas.',
    requiere_chasis: 'NO'
  }),
  r({
    sku_proveedor: 'REP-023',
    nombre_publicado: 'Cazoleta Superior Amortiguador Delantero Monroe',
    categoria: 'Suspensión',
    subcategoria: 'Cazoletas',
    marca_repuesto: 'Monroe',
    referencia_oem: '48609-0D150',
    tipo_precio: 'MOSTRAR_PRECIO',
    precio: 22900,
    stock: 16,
    condicion: 'ORIGINAL',
    compatibilidad_marca: 'Toyota',
    compatibilidad_modelo: 'Yaris',
    anio_desde: 2015,
    anio_hasta: 2020,
    motor: '1.5',
    descripcion: 'Soporte superior de amortiguador con rodamiento axial de giro integrado.',
    requiere_chasis: 'NO'
  }),
  r({
    sku_proveedor: 'REP-024',
    nombre_publicado: 'Juego de Espirales de Suspensión Trasera KYB K-Flex',
    categoria: 'Suspensión',
    subcategoria: 'Espirales',
    marca_repuesto: 'KYB',
    referencia_oem: '55330-2B000',
    tipo_precio: 'MOSTRAR_PRECIO',
    precio: 64900,
    stock: 6,
    condicion: 'ORIGINAL',
    compatibilidad_marca: 'Hyundai',
    compatibilidad_modelo: 'Santa Fe',
    anio_desde: 2013,
    anio_hasta: 2018,
    motor: '2.2 CRDi / 2.4 MPI',
    descripcion: 'Par de resortes helicoidales tratados térmicamente para carga pesada y estabilidad.',
    requiere_chasis: 'NO'
  }),
  r({
    sku_proveedor: 'REP-025',
    nombre_publicado: 'Rótula de Suspensión Inferior TRW',
    categoria: 'Suspensión',
    subcategoria: 'Rótulas',
    marca_repuesto: 'TRW',
    referencia_oem: '43330-09610',
    tipo_precio: 'MOSTRAR_PRECIO',
    precio: 17800,
    stock: 26,
    condicion: 'ORIGINAL',
    compatibilidad_marca: 'Toyota',
    compatibilidad_modelo: 'Hilux',
    anio_desde: 2016,
    anio_hasta: 2022,
    motor: '2.4 / 2.8 TDI',
    descripcion: 'Rótula delantera inferior de servicio pesado con guardapolvo de caucho cloropreno.',
    requiere_chasis: 'NO'
  }),
  r({
    sku_proveedor: 'REP-026',
    nombre_publicado: 'Buje de Bandeja Grande Trasero Corteco',
    categoria: 'Suspensión',
    subcategoria: 'Bujes',
    marca_repuesto: 'Corteco',
    referencia_oem: '54570-BB00A',
    tipo_precio: 'MOSTRAR_PRECIO',
    precio: 9900,
    stock: 35,
    condicion: 'ALTERNATIVO',
    compatibilidad_marca: 'Nissan',
    compatibilidad_modelo: 'Qashqai',
    anio_desde: 2014,
    anio_hasta: 2020,
    motor: '1.6 / 2.0',
    descripcion: 'Buje hidráulico metal-caucho para absorción de vibraciones en tren delantero.',
    requiere_chasis: 'NO'
  }),
  r({
    sku_proveedor: 'REP-027',
    nombre_publicado: 'Barra Tensora de Suspensión Trasera TRW',
    categoria: 'Suspensión',
    subcategoria: 'Barra Tensora',
    marca_repuesto: 'TRW',
    referencia_oem: '55250-2S000',
    tipo_precio: 'MOSTRAR_PRECIO',
    precio: 31500,
    stock: 9,
    condicion: 'ORIGINAL',
    compatibilidad_marca: 'Kia',
    compatibilidad_modelo: 'Sportage',
    anio_desde: 2015,
    anio_hasta: 2021,
    motor: '2.0',
    descripcion: 'Brazo de alineación y control longitudinal para suspensión multi-link trasera.',
    requiere_chasis: 'NO'
  }),
  r({
    sku_proveedor: 'REP-028',
    nombre_publicado: 'Barra de Torsión Reforzada KYB',
    categoria: 'Suspensión',
    subcategoria: 'Barra Torsión',
    marca_repuesto: 'KYB',
    referencia_oem: 'MR267983',
    tipo_precio: 'SOLO_COTIZAR',
    precio: 98000,
    stock: 5,
    condicion: 'ORIGINAL',
    compatibilidad_marca: 'Mitsubishi',
    compatibilidad_modelo: 'L200',
    anio_desde: 2015,
    anio_hasta: 2022,
    motor: '2.4 DI-D',
    descripcion: 'Barra de torsión de acero de alta resistencia para ajuste de altura del tren delantero.',
    requiere_chasis: 'SI'
  }),

  // --- MOTOR & DISTRIBUCIÓN (29-38) ---
  r({
    sku_proveedor: 'REP-029',
    nombre_publicado: 'Kit de Distribución con Bomba de Agua Gates PowerGrip',
    categoria: 'Distribución',
    subcategoria: 'Bombas de Agua',
    marca_repuesto: 'Gates',
    referencia_oem: '16100-29155',
    tipo_precio: 'MOSTRAR_PRECIO',
    precio: 89900,
    stock: 11,
    condicion: 'ORIGINAL',
    compatibilidad_marca: 'Toyota',
    compatibilidad_modelo: 'Yaris',
    anio_desde: 2014,
    anio_hasta: 2019,
    motor: '1.5 16V',
    descripcion: 'Kit completo que incluye correa sincrónica de distribución, tensor y bomba de agua con empaquetadura.',
    requiere_chasis: 'NO'
  }),
  r({
    sku_proveedor: 'REP-030',
    nombre_publicado: 'Cadena de Distribución Primaria Continental',
    categoria: 'Distribución',
    subcategoria: 'Cadenas Distribución',
    marca_repuesto: 'Continental',
    referencia_oem: '24321-2B000',
    tipo_precio: 'MOSTRAR_PRECIO',
    precio: 45000,
    stock: 14,
    condicion: 'ORIGINAL',
    compatibilidad_marca: 'Hyundai',
    compatibilidad_modelo: 'Accent',
    anio_desde: 2013,
    anio_hasta: 2022,
    motor: '1.4 / 1.6 Gamma',
    descripcion: 'Cadena silenciosa de eslabones invertidos templada por inducción.',
    requiere_chasis: 'NO'
  }),
  r({
    sku_proveedor: 'REP-031',
    nombre_publicado: 'Tensor Hidráulico de Cadena Distribución INA / Schaeffler',
    categoria: 'Distribución',
    subcategoria: 'Tensores Hidráulicos Distribución',
    marca_repuesto: 'SKF',
    referencia_oem: '24410-2B000',
    tipo_precio: 'MOSTRAR_PRECIO',
    precio: 29500,
    stock: 17,
    condicion: 'ORIGINAL',
    compatibilidad_marca: 'Kia',
    compatibilidad_modelo: 'Cerato',
    anio_desde: 2014,
    anio_hasta: 2019,
    motor: '1.6 MPI',
    descripcion: 'Tensor automático de presión de aceite con trinquete de bloqueo antiretroceso.',
    requiere_chasis: 'NO'
  }),
  r({
    sku_proveedor: 'REP-032',
    nombre_publicado: 'Juego de Anillos de Pistón Estándar STD Mahle',
    categoria: 'Motor',
    subcategoria: 'Anillos de Pistón',
    marca_repuesto: 'Mahle',
    referencia_oem: '13011-21040',
    tipo_precio: 'MOSTRAR_PRECIO',
    precio: 36900,
    stock: 12,
    condicion: 'ORIGINAL',
    compatibilidad_marca: 'Toyota',
    compatibilidad_modelo: 'Yaris',
    anio_desde: 2012,
    anio_hasta: 2018,
    motor: '1.5 1NZ-FE',
    descripcion: 'Juego completo de aros para 4 cilindros con recubrimiento de nitruro de cromo.',
    requiere_chasis: 'NO'
  }),
  r({
    sku_proveedor: 'REP-033',
    nombre_publicado: 'Juego de Pistones con Pasador Mahle STD',
    categoria: 'Motor',
    subcategoria: 'Pistones',
    marca_repuesto: 'Mahle',
    referencia_oem: '23041-2B000',
    tipo_precio: 'SOLO_COTIZAR',
    precio: 135000,
    stock: 5,
    condicion: 'ORIGINAL',
    compatibilidad_marca: 'Hyundai',
    compatibilidad_modelo: 'Elantra',
    anio_desde: 2015,
    anio_hasta: 2020,
    motor: '1.6 DOHC',
    descripcion: 'Pistones de aleación de aluminio hipereutéctica con falda recubierta de grafito.',
    requiere_chasis: 'SI'
  }),
  r({
    sku_proveedor: 'REP-034',
    nombre_publicado: 'Válvula de Admisión y Escape (Juego de 16) Mahle',
    categoria: 'Motor',
    subcategoria: 'Válvula de Admisión y Escape',
    marca_repuesto: 'Mahle',
    referencia_oem: '13711-21020',
    tipo_precio: 'MOSTRAR_PRECIO',
    precio: 48000,
    stock: 8,
    condicion: 'ORIGINAL',
    compatibilidad_marca: 'Toyota',
    compatibilidad_modelo: 'Corolla',
    anio_desde: 2014,
    anio_hasta: 2019,
    motor: '1.8 2ZR-FE',
    descripcion: 'Set de 8 válvulas de admisión y 8 válvulas de escape con vástago cromado duro.',
    requiere_chasis: 'NO'
  }),
  r({
    sku_proveedor: 'REP-035',
    nombre_publicado: 'Juego de Pernos de Culata Reforzados Ajusa',
    categoria: 'Motor',
    subcategoria: 'Pernos de Culata',
    marca_repuesto: 'Ajusa',
    referencia_oem: '81035200',
    tipo_precio: 'MOSTRAR_PRECIO',
    precio: 23900,
    stock: 20,
    condicion: 'ORIGINAL',
    compatibilidad_marca: 'Chevrolet',
    compatibilidad_modelo: 'Cruze',
    anio_desde: 2012,
    anio_hasta: 2017,
    motor: '1.8 ECOTEC',
    descripcion: 'Pernos elásticos de apriete angular para sellado óptimo de culata.',
    requiere_chasis: 'NO'
  }),
  r({
    sku_proveedor: 'REP-036',
    nombre_publicado: 'Cigüeñal Forjado de Motor Original Mahle',
    categoria: 'Motor',
    subcategoria: 'Cigüeñales',
    marca_repuesto: 'Mahle',
    referencia_oem: '23111-2B600',
    tipo_precio: 'SOLO_COTIZAR',
    precio: 380000,
    stock: 3,
    condicion: 'ORIGINAL',
    compatibilidad_marca: 'Hyundai',
    compatibilidad_modelo: 'Tucson',
    anio_desde: 2016,
    anio_hasta: 2021,
    motor: '2.0 Nu',
    descripcion: 'Cigüeñal balanceado con muñones rectificados y endurecidos por micro-aleación.',
    requiere_chasis: 'SI'
  }),
  r({
    sku_proveedor: 'REP-037',
    nombre_publicado: 'Metales de Biela y Bancada STD Mahle Clevite',
    categoria: 'Motor',
    subcategoria: 'Metales de Biela',
    marca_repuesto: 'Mahle',
    referencia_oem: '23060-2B000',
    tipo_precio: 'MOSTRAR_PRECIO',
    precio: 27900,
    stock: 15,
    condicion: 'ORIGINAL',
    compatibilidad_marca: 'Kia',
    compatibilidad_modelo: 'Rio',
    anio_desde: 2013,
    anio_hasta: 2018,
    motor: '1.4',
    descripcion: 'Cojinetes trimetálicos de bancada y biela con alta resistencia a fatiga.',
    requiere_chasis: 'NO'
  }),
  r({
    sku_proveedor: 'REP-038',
    nombre_publicado: 'Tapa de Válvulas con Empaquetadura Valeo',
    categoria: 'Motor',
    subcategoria: 'Tapa de Válvula',
    marca_repuesto: 'Valeo',
    referencia_oem: '55564395',
    tipo_precio: 'MOSTRAR_PRECIO',
    precio: 58900,
    stock: 9,
    condicion: 'ALTERNATIVO',
    compatibilidad_marca: 'Chevrolet',
    compatibilidad_modelo: 'Cruze',
    anio_desde: 2011,
    anio_hasta: 2016,
    motor: '1.8',
    descripcion: 'Tapa de culata con válvula PCV y empaque de silicona para evitar fugas de aceite.',
    requiere_chasis: 'NO'
  }),

  // --- DIRECCIÓN (39-46) ---
  r({
    sku_proveedor: 'REP-039',
    nombre_publicado: 'Terminal de Dirección Exterior Izquierdo TRW',
    categoria: 'Dirección',
    subcategoria: 'Terminal de Dirección',
    marca_repuesto: 'TRW',
    referencia_oem: '45047-09280',
    tipo_precio: 'MOSTRAR_PRECIO',
    precio: 16900,
    stock: 24,
    condicion: 'ORIGINAL',
    compatibilidad_marca: 'Toyota',
    compatibilidad_modelo: 'Corolla',
    anio_desde: 2014,
    anio_hasta: 2019,
    motor: '1.8',
    descripcion: 'Extremo de dirección con rosca de precisión y fuelles sellados de fábrica.',
    requiere_chasis: 'NO'
  }),
  r({
    sku_proveedor: 'REP-040',
    nombre_publicado: 'Terminal Axial de Dirección (Articulación) TRW',
    categoria: 'Dirección',
    subcategoria: 'Terminal Axial',
    marca_repuesto: 'TRW',
    referencia_oem: '45503-02060',
    tipo_precio: 'MOSTRAR_PRECIO',
    precio: 14900,
    stock: 28,
    condicion: 'ORIGINAL',
    compatibilidad_marca: 'Toyota',
    compatibilidad_modelo: 'Corolla',
    anio_desde: 2014,
    anio_hasta: 2019,
    motor: '1.8',
    descripcion: 'Barra axial interior para cremallera de dirección asistida eléctrica.',
    requiere_chasis: 'NO'
  }),
  r({
    sku_proveedor: 'REP-041',
    nombre_publicado: 'Cremallera de Dirección Electro-Asistida EPS TRW',
    categoria: 'Dirección',
    subcategoria: 'Cremallera de Dirección',
    marca_repuesto: 'TRW',
    referencia_oem: '56500-1R000',
    tipo_precio: 'SOLO_COTIZAR',
    precio: 285000,
    stock: 4,
    condicion: 'ORIGINAL',
    compatibilidad_marca: 'Hyundai',
    compatibilidad_modelo: 'Accent',
    anio_desde: 2012,
    anio_hasta: 2018,
    motor: '1.4 / 1.6',
    descripcion: 'Caja de dirección completa con sensor de torque y barras axiales incorporadas.',
    requiere_chasis: 'SI'
  }),
  r({
    sku_proveedor: 'REP-042',
    nombre_publicado: 'Bomba de Dirección Hidráulica Bosch',
    categoria: 'Dirección',
    subcategoria: 'Bomba de Dirección',
    marca_repuesto: 'Bosch',
    referencia_oem: '49110-3X000',
    tipo_precio: 'MOSTRAR_PRECIO',
    precio: 112000,
    stock: 7,
    condicion: 'ORIGINAL',
    compatibilidad_marca: 'Nissan',
    compatibilidad_modelo: 'Navara',
    anio_desde: 2010,
    anio_hasta: 2016,
    motor: '2.5 dCi',
    descripcion: 'Bomba hidráulica de paletas de alta presión con polea de accionamiento.',
    requiere_chasis: 'NO'
  }),
  r({
    sku_proveedor: 'REP-043',
    nombre_publicado: 'Módulo EPS Columna de Dirección Denso',
    categoria: 'Dirección',
    subcategoria: 'Módulo EPS',
    marca_repuesto: 'Denso',
    referencia_oem: '89650-52050',
    tipo_precio: 'SOLO_COTIZAR',
    precio: 195000,
    stock: 3,
    condicion: 'ORIGINAL',
    compatibilidad_marca: 'Toyota',
    compatibilidad_modelo: 'Yaris',
    anio_desde: 2015,
    anio_hasta: 2020,
    motor: '1.5',
    descripcion: 'Unidad de control electrónico de asistencia eléctrica de dirección.',
    requiere_chasis: 'SI'
  }),
  r({
    sku_proveedor: 'REP-044',
    nombre_publicado: 'Junta Cardánica de Columna de Dirección Valeo',
    categoria: 'Dirección',
    subcategoria: 'Junta Cardánica',
    marca_repuesto: 'Valeo',
    referencia_oem: '56400-2B000',
    tipo_precio: 'MOSTRAR_PRECIO',
    precio: 34500,
    stock: 12,
    condicion: 'ALTERNATIVO',
    compatibilidad_marca: 'Hyundai',
    compatibilidad_modelo: 'Santa Fe',
    anio_desde: 2013,
    anio_hasta: 2018,
    motor: '2.2 / 2.4',
    descripcion: 'Acople flexible intermedio con cruceta reforzada para columna de dirección.',
    requiere_chasis: 'NO'
  }),
  r({
    sku_proveedor: 'REP-045',
    nombre_publicado: 'Correa Dirección Hidráulica Gates Micro-V',
    categoria: 'Dirección',
    subcategoria: 'Correa Dirección Hidráulica',
    marca_repuesto: 'Gates',
    referencia_oem: '4PK855',
    tipo_precio: 'MOSTRAR_PRECIO',
    precio: 8900,
    stock: 30,
    condicion: 'ORIGINAL',
    compatibilidad_marca: 'Chevrolet',
    compatibilidad_modelo: 'Sail',
    anio_desde: 2011,
    anio_hasta: 2017,
    motor: '1.4',
    descripcion: 'Correa poli-V de perfil acanalado de caucho EPDM resistente a altas temperaturas.',
    requiere_chasis: 'NO'
  }),
  r({
    sku_proveedor: 'REP-046',
    nombre_publicado: 'Columna de Dirección Ajustable Original Bosch',
    categoria: 'Dirección',
    subcategoria: 'Columna de Dirección',
    marca_repuesto: 'Bosch',
    referencia_oem: '56310-1W100',
    tipo_precio: 'SOLO_COTIZAR',
    precio: 210000,
    stock: 2,
    condicion: 'ORIGINAL',
    compatibilidad_marca: 'Kia',
    compatibilidad_modelo: 'Rio',
    anio_desde: 2014,
    anio_hasta: 2019,
    motor: '1.4',
    descripcion: 'Conjunto de eje de columna telescópica colapsable con soporte de bloqueo.',
    requiere_chasis: 'SI'
  }),

  // --- EMBRAGUE (47-54) ---
  r({
    sku_proveedor: 'REP-047',
    nombre_publicado: 'Kit de Embrague Completo Sachs (Prensa + Disco + Rodamiento)',
    categoria: 'Embrague',
    subcategoria: 'Kit de Embragues',
    marca_repuesto: 'Sachs',
    referencia_oem: '3000951025',
    tipo_precio: 'MOSTRAR_PRECIO',
    precio: 119900,
    stock: 10,
    condicion: 'ORIGINAL',
    compatibilidad_marca: 'Toyota',
    compatibilidad_modelo: 'Hilux',
    anio_desde: 2015,
    anio_hasta: 2021,
    motor: '2.4 / 2.8 TDI',
    descripcion: 'Kit de 3 componentes con plato de presión diafragma, disco orgánico amortiguado y rodamiento de empuje.',
    requiere_chasis: 'NO'
  }),
  r({
    sku_proveedor: 'REP-048',
    nombre_publicado: 'Kit de Embrague LuK RepSet con Rodamiento Hidráulico',
    categoria: 'Embrague',
    subcategoria: 'Kit de Embragues',
    marca_repuesto: 'Luk',
    referencia_oem: '620308633',
    tipo_precio: 'MOSTRAR_PRECIO',
    precio: 98500,
    stock: 12,
    condicion: 'ORIGINAL',
    compatibilidad_marca: 'Chevrolet',
    compatibilidad_modelo: 'Sail',
    anio_desde: 2011,
    anio_hasta: 2018,
    motor: '1.4 / 1.5',
    descripcion: 'Sistema de accionamiento suave y larga vida útil diseñado según especificaciones OEM.',
    requiere_chasis: 'NO'
  }),
  r({
    sku_proveedor: 'REP-049',
    nombre_publicado: 'Bomba Principal de Embrague Valeo',
    categoria: 'Embrague',
    subcategoria: 'Bombas de Embrague',
    marca_repuesto: 'Valeo',
    referencia_oem: '41605-1R000',
    tipo_precio: 'MOSTRAR_PRECIO',
    precio: 28900,
    stock: 18,
    condicion: 'ORIGINAL',
    compatibilidad_marca: 'Hyundai',
    compatibilidad_modelo: 'Accent',
    anio_desde: 2012,
    anio_hasta: 2022,
    motor: '1.4 / 1.6',
    descripcion: 'Cilindro maestro de embrague acoplado al pedal para accionamiento hidráulico.',
    requiere_chasis: 'NO'
  }),
  r({
    sku_proveedor: 'REP-050',
    nombre_publicado: 'Cilindro Auxiliar de Embrague (Bombín Esclavo) Sachs',
    categoria: 'Embrague',
    subcategoria: 'Cilindro de Embragues',
    marca_repuesto: 'Sachs',
    referencia_oem: '31470-52050',
    tipo_precio: 'MOSTRAR_PRECIO',
    precio: 24500,
    stock: 20,
    condicion: 'ORIGINAL',
    compatibilidad_marca: 'Toyota',
    compatibilidad_modelo: 'Yaris',
    anio_desde: 2014,
    anio_hasta: 2020,
    motor: '1.5',
    descripcion: 'Bombín receptor de caja de cambios con purgado rápido y sello de nitrilo.',
    requiere_chasis: 'NO'
  }),
  r({
    sku_proveedor: 'REP-051',
    nombre_publicado: 'Volante de Inercia Bimasa LuK Dual Mass Flywheel',
    categoria: 'Embrague',
    subcategoria: 'Volantes de Motor',
    marca_repuesto: 'Luk',
    referencia_oem: '415024410',
    tipo_precio: 'SOLO_COTIZAR',
    precio: 360000,
    stock: 4,
    condicion: 'ORIGINAL',
    compatibilidad_marca: 'Volkswagen',
    compatibilidad_modelo: 'Golf',
    anio_desde: 2014,
    anio_hasta: 2020,
    motor: '2.0 TDI',
    descripcion: 'Volante bimasa para absorción de vibraciones torsionales en cajas manuales y DSG.',
    requiere_chasis: 'SI'
  }),
  r({
    sku_proveedor: 'REP-052',
    nombre_publicado: 'Horquilla de Desembrague Reforzada Valeo',
    categoria: 'Embrague',
    subcategoria: 'Horquilla de Embrague',
    marca_repuesto: 'Valeo',
    referencia_oem: '31204-52010',
    tipo_precio: 'MOSTRAR_PRECIO',
    precio: 16800,
    stock: 15,
    condicion: 'ALTERNATIVO',
    compatibilidad_marca: 'Toyota',
    compatibilidad_modelo: 'Yaris',
    anio_desde: 2013,
    anio_hasta: 2018,
    motor: '1.3 / 1.5',
    descripcion: 'Palanca de accionamiento de rodamiento de empuje en acero forjado.',
    requiere_chasis: 'NO'
  }),
  r({
    sku_proveedor: 'REP-053',
    nombre_publicado: 'Piola de Embrague Reforzada Valeo',
    categoria: 'Embrague',
    subcategoria: 'Piola Embrague',
    marca_repuesto: 'Valeo',
    referencia_oem: '23710-68L00',
    tipo_precio: 'MOSTRAR_PRECIO',
    precio: 17500,
    stock: 22,
    condicion: 'ORIGINAL',
    compatibilidad_marca: 'Suzuki',
    compatibilidad_modelo: 'Swift',
    anio_desde: 2012,
    anio_hasta: 2017,
    motor: '1.2',
    descripcion: 'Cable de embrague de acero trenzado con tuerca de regulación milimétrica.',
    requiere_chasis: 'NO'
  }),
  r({
    sku_proveedor: 'REP-054',
    nombre_publicado: 'Cilindro Esclavo Central Concéntrico CSC LuK',
    categoria: 'Embrague',
    subcategoria: 'Cilindro de Embragues',
    marca_repuesto: 'Luk',
    referencia_oem: '510007310',
    tipo_precio: 'MOSTRAR_PRECIO',
    precio: 49900,
    stock: 14,
    condicion: 'ORIGINAL',
    compatibilidad_marca: 'Ford',
    compatibilidad_modelo: 'EcoSport',
    anio_desde: 2013,
    anio_hasta: 2019,
    motor: '1.5 / 1.6 / 2.0',
    descripcion: 'Rodamiento hidráulico de empuje concéntrico interno para caja manual IB5.',
    requiere_chasis: 'NO'
  }),

  // --- REFRIGERACIÓN & CLIMATIZACIÓN (55-64) ---
  r({
    sku_proveedor: 'REP-055',
    nombre_publicado: 'Radiador de Agua de Motor en Aluminio Denso',
    categoria: 'Refrigeración',
    subcategoria: 'Radiador de Agua',
    marca_repuesto: 'Denso',
    referencia_oem: '16400-21180',
    tipo_precio: 'MOSTRAR_PRECIO',
    precio: 64900,
    stock: 8,
    condicion: 'ORIGINAL',
    compatibilidad_marca: 'Toyota',
    compatibilidad_modelo: 'Yaris',
    anio_desde: 2015,
    anio_hasta: 2021,
    motor: '1.5',
    descripcion: 'Radiador de panel de aluminio soldado con tanques plásticos resistentes a presión.',
    requiere_chasis: 'NO'
  }),
  r({
    sku_proveedor: 'REP-056',
    nombre_publicado: 'Termostato de Refrigeración 82°C Gates',
    categoria: 'Refrigeración',
    subcategoria: 'Termostato',
    marca_repuesto: 'Gates',
    referencia_oem: '90916-03093',
    tipo_precio: 'MOSTRAR_PRECIO',
    precio: 13900,
    stock: 35,
    condicion: 'ORIGINAL',
    compatibilidad_marca: 'Toyota',
    compatibilidad_modelo: 'Corolla',
    anio_desde: 2014,
    anio_hasta: 2020,
    motor: '1.8',
    descripcion: 'Válvula termostática con empaque de goma y cápsula de cera calibrada a 82°C.',
    requiere_chasis: 'NO'
  }),
  r({
    sku_proveedor: 'REP-057',
    nombre_publicado: 'Bomba de Agua con Empaque Gates PowerGrip',
    categoria: 'Refrigeración',
    subcategoria: 'Bombas de Agua',
    marca_repuesto: 'Gates',
    referencia_oem: '25100-2B000',
    tipo_precio: 'MOSTRAR_PRECIO',
    precio: 32900,
    stock: 19,
    condicion: 'ORIGINAL',
    compatibilidad_marca: 'Hyundai',
    compatibilidad_modelo: 'Accent',
    anio_desde: 2012,
    anio_hasta: 2022,
    motor: '1.4 / 1.6',
    descripcion: 'Bomba centrífuga de refrigerante con rodamiento sellado y rotor anti-cavitación.',
    requiere_chasis: 'NO'
  }),
  r({
    sku_proveedor: 'REP-058',
    nombre_publicado: 'Depósito de Expansión de Refrigerante Valeo',
    categoria: 'Refrigeración',
    subcategoria: 'Depósito Radiador',
    marca_repuesto: 'Valeo',
    referencia_oem: '13220124',
    tipo_precio: 'MOSTRAR_PRECIO',
    precio: 18500,
    stock: 16,
    condicion: 'ALTERNATIVO',
    compatibilidad_marca: 'Chevrolet',
    compatibilidad_modelo: 'Cruze',
    anio_desde: 2011,
    anio_hasta: 2016,
    motor: '1.8',
    descripcion: 'Vaso de expansión transparente de polipropileno resistente a alta presión térmica.',
    requiere_chasis: 'NO'
  }),
  r({
    sku_proveedor: 'REP-059',
    nombre_publicado: 'Electroventilador Completo con Aspas y Encausador Denso',
    categoria: 'Refrigeración',
    subcategoria: 'Electroventilador',
    marca_repuesto: 'Denso',
    referencia_oem: '16363-0D080',
    tipo_precio: 'MOSTRAR_PRECIO',
    precio: 78000,
    stock: 7,
    condicion: 'ORIGINAL',
    compatibilidad_marca: 'Toyota',
    compatibilidad_modelo: 'Yaris',
    anio_desde: 2016,
    anio_hasta: 2021,
    motor: '1.5',
    descripcion: 'Conjunto de motor eléctrico de 12V con aspas balanceadas y difusor aerodinámico.',
    requiere_chasis: 'NO'
  }),
  r({
    sku_proveedor: 'REP-060',
    nombre_publicado: 'Manguera Superior de Radiador Gates',
    categoria: 'Refrigeración',
    subcategoria: 'Manguera Radiador',
    marca_repuesto: 'Gates',
    referencia_oem: '16571-0D120',
    tipo_precio: 'MOSTRAR_PRECIO',
    precio: 11500,
    stock: 25,
    condicion: 'ORIGINAL',
    compatibilidad_marca: 'Toyota',
    compatibilidad_modelo: 'Corolla',
    anio_desde: 2014,
    anio_hasta: 2019,
    motor: '1.8',
    descripcion: 'Manguera de refrigeración moldeada en caucho EPDM reforzada con tejido de poliéster.',
    requiere_chasis: 'NO'
  }),
  r({
    sku_proveedor: 'REP-061',
    nombre_publicado: 'Compresor de Aire Acondicionado Denso 10S17C',
    categoria: 'Calefacción y Aire Acondicionado',
    subcategoria: 'Compresor',
    marca_repuesto: 'Denso',
    referencia_oem: '88310-0D330',
    tipo_precio: 'SOLO_COTIZAR',
    precio: 245000,
    stock: 5,
    condicion: 'ORIGINAL',
    compatibilidad_marca: 'Toyota',
    compatibilidad_modelo: 'Yaris',
    anio_desde: 2015,
    anio_hasta: 2021,
    motor: '1.5',
    descripcion: 'Compresor rotativo de pistones con embrague electromagnético para gas refrigerante R134a.',
    requiere_chasis: 'SI'
  }),
  r({
    sku_proveedor: 'REP-062',
    nombre_publicado: 'Condensador de Climatización con Filtro Secador Valeo',
    categoria: 'Calefacción y Aire Acondicionado',
    subcategoria: 'Condensador',
    marca_repuesto: 'Valeo',
    referencia_oem: '97606-1R000',
    tipo_precio: 'MOSTRAR_PRECIO',
    precio: 68900,
    stock: 8,
    condicion: 'ORIGINAL',
    compatibilidad_marca: 'Hyundai',
    compatibilidad_modelo: 'Accent',
    anio_desde: 2012,
    anio_hasta: 2022,
    motor: '1.4 / 1.6',
    descripcion: 'Intercambiador de calor de flujo paralelo de aluminio para circuito de aire acondicionado.',
    requiere_chasis: 'NO'
  }),
  r({
    sku_proveedor: 'REP-063',
    nombre_publicado: 'Radiador de Calefacción Interior Denso',
    categoria: 'Calefacción y Aire Acondicionado',
    subcategoria: 'Radiador de Calefacción',
    marca_repuesto: 'Denso',
    referencia_oem: '87107-52090',
    tipo_precio: 'MOSTRAR_PRECIO',
    precio: 42000,
    stock: 9,
    condicion: 'ORIGINAL',
    compatibilidad_marca: 'Toyota',
    compatibilidad_modelo: 'Yaris',
    anio_desde: 2014,
    anio_hasta: 2020,
    motor: '1.3 / 1.5',
    descripcion: 'Núcleo calefactor de cabina de aluminio para climatización del habitáculo.',
    requiere_chasis: 'NO'
  }),
  r({
    sku_proveedor: 'REP-064',
    nombre_publicado: 'Evaporador de Aire Acondicionado Valeo',
    categoria: 'Calefacción y Aire Acondicionado',
    subcategoria: 'Evaporador',
    marca_repuesto: 'Valeo',
    referencia_oem: '97139-2E000',
    tipo_precio: 'MOSTRAR_PRECIO',
    precio: 56000,
    stock: 6,
    condicion: 'ALTERNATIVO',
    compatibilidad_marca: 'Hyundai',
    compatibilidad_modelo: 'Tucson',
    anio_desde: 2016,
    anio_hasta: 2021,
    motor: '2.0',
    descripcion: 'Panel evaporador interno con tratamiento antibacterias y anticorrosión.',
    requiere_chasis: 'NO'
  }),

  // --- ENCENDIDO & ELÉCTRICO (65-74) ---
  r({
    sku_proveedor: 'REP-065',
    nombre_publicado: 'Juego de 4 Bujías de Iridio NGK Laser Iridium ILKAR7B11',
    categoria: 'Encendido',
    subcategoria: 'Bujías',
    marca_repuesto: 'NGK',
    referencia_oem: '90919-01253',
    tipo_precio: 'MOSTRAR_PRECIO',
    precio: 36900,
    stock: 40,
    condicion: 'ORIGINAL',
    compatibilidad_marca: 'Toyota',
    compatibilidad_modelo: 'Corolla',
    anio_desde: 2014,
    anio_hasta: 2021,
    motor: '1.8 / 2.0',
    descripcion: 'Bujías de alto rendimiento con punta de iridio ultrafina y electrodo de platino.',
    requiere_chasis: 'NO'
  }),
  r({
    sku_proveedor: 'REP-066',
    nombre_publicado: 'Bobina de Encendido Individual Bosch Coil-on-Plug',
    categoria: 'Encendido',
    subcategoria: 'Bobinas',
    marca_repuesto: 'Bosch',
    referencia_oem: '27301-2B010',
    tipo_precio: 'MOSTRAR_PRECIO',
    precio: 29900,
    stock: 24,
    condicion: 'ORIGINAL',
    compatibilidad_marca: 'Hyundai',
    compatibilidad_modelo: 'Accent',
    anio_desde: 2013,
    anio_hasta: 2022,
    motor: '1.4 / 1.6',
    descripcion: 'Bobina tipo lápiz para encendido directo electrónico de alto voltaje y chispa estable.',
    requiere_chasis: 'NO'
  }),
  r({
    sku_proveedor: 'REP-067',
    nombre_publicado: 'Juego de Cables de Bujía de Silicona NGK',
    categoria: 'Encendido',
    subcategoria: 'Cables de Bujía',
    marca_repuesto: 'NGK',
    referencia_oem: 'RC-NX14',
    tipo_precio: 'MOSTRAR_PRECIO',
    precio: 21900,
    stock: 18,
    condicion: 'ORIGINAL',
    compatibilidad_marca: 'Nissan',
    compatibilidad_modelo: 'V16',
    anio_desde: 2005,
    anio_hasta: 2011,
    motor: '1.6 16V Twin Cam',
    descripcion: 'Juego de 4 cables antiparasitarios con terminales vulcanizados resistentes a altas temperaturas.',
    requiere_chasis: 'NO'
  }),
  r({
    sku_proveedor: 'REP-068',
    nombre_publicado: 'Motor de Partida / Arranque 12V 1.0kW Valeo',
    categoria: 'Encendido',
    subcategoria: 'Motor de Partida',
    marca_repuesto: 'Valeo',
    referencia_oem: '36100-2B020',
    tipo_precio: 'MOSTRAR_PRECIO',
    precio: 89900,
    stock: 8,
    condicion: 'ORIGINAL',
    compatibilidad_marca: 'Kia',
    compatibilidad_modelo: 'Rio',
    anio_desde: 2014,
    anio_hasta: 2019,
    motor: '1.4 / 1.6',
    descripcion: 'Motor de arranque de imán permanente con solenoide reforzado y piñón de 8 dientes.',
    requiere_chasis: 'NO'
  }),
  r({
    sku_proveedor: 'REP-069',
    nombre_publicado: 'Alternador 12V 90A con Polea Libre Valeo',
    categoria: 'Eléctrico',
    subcategoria: 'Alternador',
    marca_repuesto: 'Valeo',
    referencia_oem: '37300-2B101',
    tipo_precio: 'MOSTRAR_PRECIO',
    precio: 149000,
    stock: 6,
    condicion: 'ORIGINAL',
    compatibilidad_marca: 'Hyundai',
    compatibilidad_modelo: 'Elantra',
    anio_desde: 2015,
    anio_hasta: 2020,
    motor: '1.6',
    descripcion: 'Generador eléctrico de alta eficiencia con regulador de voltaje electrónico integrado.',
    requiere_chasis: 'NO'
  }),
  r({
    sku_proveedor: 'REP-070',
    nombre_publicado: 'Batería Automotriz 12V 60Ah 540CCA Willard Titanio',
    categoria: 'Eléctrico',
    subcategoria: 'Baterías',
    marca_repuesto: 'Willard',
    referencia_oem: 'NS60L-W',
    tipo_precio: 'MOSTRAR_PRECIO',
    precio: 68900,
    stock: 20,
    condicion: 'ORIGINAL',
    compatibilidad_marca: 'Toyota',
    compatibilidad_modelo: 'Corolla',
    anio_desde: 2014,
    anio_hasta: 2022,
    motor: '1.8',
    descripcion: 'Batería libre de mantenimiento con tecnología de aleación plomo-calcio-plata.',
    requiere_chasis: 'NO'
  }),
  r({
    sku_proveedor: 'REP-071',
    nombre_publicado: 'Comando de Luces y Neblineros en Columna Valeo',
    categoria: 'Eléctrico',
    subcategoria: 'Comando de Luces',
    marca_repuesto: 'Valeo',
    referencia_oem: '93410-1R000',
    tipo_precio: 'MOSTRAR_PRECIO',
    precio: 29900,
    stock: 14,
    condicion: 'ORIGINAL',
    compatibilidad_marca: 'Hyundai',
    compatibilidad_modelo: 'Accent',
    anio_desde: 2012,
    anio_hasta: 2022,
    motor: '1.4 / 1.6',
    descripcion: 'Mando multifunción de luces altas, bajas, intermitentes y neblineros delanteros/traseros.',
    requiere_chasis: 'NO'
  }),
  r({
    sku_proveedor: 'REP-072',
    nombre_publicado: 'Botonera Principal Alza Vidrios Conductor Bosch',
    categoria: 'Eléctrico',
    subcategoria: 'Botones Alza Vidrios',
    marca_repuesto: 'Bosch',
    referencia_oem: '84820-0D140',
    tipo_precio: 'MOSTRAR_PRECIO',
    precio: 34900,
    stock: 12,
    condicion: 'ALTERNATIVO',
    compatibilidad_marca: 'Toyota',
    compatibilidad_modelo: 'Yaris',
    anio_desde: 2015,
    anio_hasta: 2020,
    motor: '1.5',
    descripcion: 'Interruptor cuádruple de ventanas eléctricas con función Auto Down/Up y bloqueo de lunas.',
    requiere_chasis: 'NO'
  }),
  r({
    sku_proveedor: 'REP-073',
    nombre_publicado: 'Juego de Plumillas Limpiaparabrisas Bosch Aerotwin',
    categoria: 'Eléctrico',
    subcategoria: 'Limpia Parabrisas',
    marca_repuesto: 'Bosch',
    referencia_oem: 'A929S',
    tipo_precio: 'MOSTRAR_PRECIO',
    precio: 19990,
    stock: 45,
    condicion: 'ORIGINAL',
    compatibilidad_marca: 'Volkswagen',
    compatibilidad_modelo: 'Golf',
    anio_desde: 2014,
    anio_hasta: 2021,
    motor: '1.4 TSI',
    descripcion: 'Par de escobillas planas aerodinámicas de goma Power Protection Plus con grafito.',
    requiere_chasis: 'NO'
  }),
  r({
    sku_proveedor: 'REP-074',
    nombre_publicado: 'Pedal de Acelerador Electrónico con Sensor Hall Denso',
    categoria: 'Eléctrico',
    subcategoria: 'Pedal Acelerador',
    marca_repuesto: 'Denso',
    referencia_oem: '78110-52030',
    tipo_precio: 'SOLO_COTIZAR',
    precio: 82000,
    stock: 5,
    condicion: 'ORIGINAL',
    compatibilidad_marca: 'Toyota',
    compatibilidad_modelo: 'Yaris',
    anio_desde: 2016,
    anio_hasta: 2021,
    motor: '1.5',
    descripcion: 'Módulo de acelerador Drive-by-Wire con potenciómetro dual inductivo sin contacto.',
    requiere_chasis: 'SI'
  }),

  // --- SENSORES (75-84) ---
  r({
    sku_proveedor: 'REP-075',
    nombre_publicado: 'Sensor de Oxígeno Lambda Delantero Pre-Catalítico Bosch',
    categoria: 'Sensores',
    subcategoria: 'Sensor de Oxígeno',
    marca_repuesto: 'Bosch',
    referencia_oem: '89467-52060',
    tipo_precio: 'MOSTRAR_PRECIO',
    precio: 49900,
    stock: 18,
    condicion: 'ORIGINAL',
    compatibilidad_marca: 'Toyota',
    compatibilidad_modelo: 'Yaris',
    anio_desde: 2015,
    anio_hasta: 2021,
    motor: '1.5 16V',
    descripcion: 'Sonda lambda de banda ancha de 4 cables con elemento cerámico calefactor rápido.',
    requiere_chasis: 'NO'
  }),
  r({
    sku_proveedor: 'REP-076',
    nombre_publicado: 'Sensor de Flujo de Masa de Aire (Flujómetro / MAF) Denso',
    categoria: 'Sensores',
    subcategoria: 'Flujómetro',
    marca_repuesto: 'Denso',
    referencia_oem: '22204-22010',
    tipo_precio: 'MOSTRAR_PRECIO',
    precio: 44500,
    stock: 14,
    condicion: 'ORIGINAL',
    compatibilidad_marca: 'Toyota',
    compatibilidad_modelo: 'Corolla',
    anio_desde: 2012,
    anio_hasta: 2018,
    motor: '1.8',
    descripcion: 'Medidor de caudal de aire tipo hilo caliente para inyección electrónica multipunto.',
    requiere_chasis: 'NO'
  }),
  r({
    sku_proveedor: 'REP-077',
    nombre_publicado: 'Sensor de Posición de Cigüeñal (CKP) Bosch',
    categoria: 'Sensores',
    subcategoria: 'Sensor Posición Cigüeñal',
    marca_repuesto: 'Bosch',
    referencia_oem: '39180-2B000',
    tipo_precio: 'MOSTRAR_PRECIO',
    precio: 22900,
    stock: 26,
    condicion: 'ORIGINAL',
    compatibilidad_marca: 'Hyundai',
    compatibilidad_modelo: 'Accent',
    anio_desde: 2013,
    anio_hasta: 2022,
    motor: '1.4 / 1.6',
    descripcion: 'Sensor inductivo de RPM y posición del cigüeñal con cable mallado resistente a temperatura.',
    requiere_chasis: 'NO'
  }),
  r({
    sku_proveedor: 'REP-078',
    nombre_publicado: 'Sensor de Presión Absoluta del Múltiple (MAP) Bosch',
    categoria: 'Sensores',
    subcategoria: 'Sensor MAP',
    marca_repuesto: 'Bosch',
    referencia_oem: '39300-2B000',
    tipo_precio: 'MOSTRAR_PRECIO',
    precio: 24900,
    stock: 22,
    condicion: 'ORIGINAL',
    compatibilidad_marca: 'Kia',
    compatibilidad_modelo: 'Rio',
    anio_desde: 2014,
    anio_hasta: 2019,
    motor: '1.4',
    descripcion: 'Sensor piezoeléctrico de presión y temperatura de admisión de 4 pines.',
    requiere_chasis: 'NO'
  }),
  r({
    sku_proveedor: 'REP-079',
    nombre_publicado: 'Sensor de Velocidad de Rueda ABS Delantero Bosch',
    categoria: 'Sensores',
    subcategoria: 'Sensor ABS',
    marca_repuesto: 'Bosch',
    referencia_oem: '89543-0D040',
    tipo_precio: 'MOSTRAR_PRECIO',
    precio: 19900,
    stock: 20,
    condicion: 'ORIGINAL',
    compatibilidad_marca: 'Toyota',
    compatibilidad_modelo: 'Yaris',
    anio_desde: 2016,
    anio_hasta: 2021,
    motor: '1.5',
    descripcion: 'Sensor magnético activo para sistema de control de estabilidad y frenos antibloqueo.',
    requiere_chasis: 'NO'
  }),
  r({
    sku_proveedor: 'REP-080',
    nombre_publicado: 'Sensor de Posición de Árbol de Levas (CMP) Denso',
    categoria: 'Sensores',
    subcategoria: 'Sensor Posición Eje Leva',
    marca_repuesto: 'Denso',
    referencia_oem: '90919-05060',
    tipo_precio: 'MOSTRAR_PRECIO',
    precio: 23500,
    stock: 25,
    condicion: 'ORIGINAL',
    compatibilidad_marca: 'Toyota',
    compatibilidad_modelo: 'Corolla',
    anio_desde: 2014,
    anio_hasta: 2019,
    motor: '1.8 Dual VVT-i',
    descripcion: 'Sensor Hall de sincronización de fase de válvulas para culata de motor.',
    requiere_chasis: 'NO'
  }),
  r({
    sku_proveedor: 'REP-081',
    nombre_publicado: 'Sensor de Temperatura de Refrigerante (ECT) Bosch',
    categoria: 'Sensores',
    subcategoria: 'Sensor de Temperatura',
    marca_repuesto: 'Bosch',
    referencia_oem: '39220-38030',
    tipo_precio: 'MOSTRAR_PRECIO',
    precio: 11900,
    stock: 35,
    condicion: 'ORIGINAL',
    compatibilidad_marca: 'Hyundai',
    compatibilidad_modelo: 'Tucson',
    anio_desde: 2016,
    anio_hasta: 2021,
    motor: '2.0',
    descripcion: 'Termistor NTC de 2 pines para lectura de temperatura de motor hacia la ECU.',
    requiere_chasis: 'NO'
  }),
  r({
    sku_proveedor: 'REP-082',
    nombre_publicado: 'Bulbo Sensor de Presión de Aceite de Motor Bosch',
    categoria: 'Sensores',
    subcategoria: 'Bulbo Presión Aceite',
    marca_repuesto: 'Bosch',
    referencia_oem: '83530-60020',
    tipo_precio: 'MOSTRAR_PRECIO',
    precio: 9500,
    stock: 40,
    condicion: 'ORIGINAL',
    compatibilidad_marca: 'Toyota',
    compatibilidad_modelo: 'Hilux',
    anio_desde: 2015,
    anio_hasta: 2022,
    motor: '2.4 / 2.8 TDI',
    descripcion: 'Interruptor manométrico con rosca cónica para testigo de presión de lubricación.',
    requiere_chasis: 'NO'
  }),
  r({
    sku_proveedor: 'REP-083',
    nombre_publicado: 'Sensor de Detonación / Golpe (Knock Sensor) Bosch',
    categoria: 'Sensores',
    subcategoria: 'Sensor de Golpe',
    marca_repuesto: 'Bosch',
    referencia_oem: '39250-2B000',
    tipo_precio: 'MOSTRAR_PRECIO',
    precio: 18900,
    stock: 19,
    condicion: 'ORIGINAL',
    compatibilidad_marca: 'Kia',
    compatibilidad_modelo: 'Cerato',
    anio_desde: 2014,
    anio_hasta: 2019,
    motor: '1.6',
    descripcion: 'Sensor piezoeléctrico no resonante para corrección del mapa de avance de encendido.',
    requiere_chasis: 'NO'
  }),
  r({
    sku_proveedor: 'REP-084',
    nombre_publicado: 'Cinta Espiral de Airbag con Sensor de Ángulo Valeo',
    categoria: 'Sensores',
    subcategoria: 'Cinta de Airbag',
    marca_repuesto: 'Valeo',
    referencia_oem: '84306-0K050',
    tipo_precio: 'SOLO_COTIZAR',
    precio: 38900,
    stock: 8,
    condicion: 'ORIGINAL',
    compatibilidad_marca: 'Toyota',
    compatibilidad_modelo: 'Hilux',
    anio_desde: 2016,
    anio_hasta: 2021,
    motor: '2.4 / 2.8',
    descripcion: 'Clock spring conductor para airbag de volante, bocina y mandos satelitales.',
    requiere_chasis: 'SI'
  }),

  // --- TRANSMISIÓN, EJES & RODAMIENTOS (85-94) ---
  r({
    sku_proveedor: 'REP-085',
    nombre_publicado: 'Rodamiento de Rueda Delantero con Anillo Magnético ABS SKF',
    categoria: 'Rodamientos',
    subcategoria: 'Rodamiento de Rueda',
    marca_repuesto: 'SKF',
    referencia_oem: 'VKBA6831',
    tipo_precio: 'MOSTRAR_PRECIO',
    precio: 29900,
    stock: 24,
    condicion: 'ORIGINAL',
    compatibilidad_marca: 'Toyota',
    compatibilidad_modelo: 'Yaris',
    anio_desde: 2015,
    anio_hasta: 2021,
    motor: '1.5',
    descripcion: 'Rodamiento de doble hilera de bolas con sello de encoder magnético para ABS.',
    requiere_chasis: 'NO'
  }),
  r({
    sku_proveedor: 'REP-086',
    nombre_publicado: 'Maza de Rueda Trasera Completa con Rodamiento SKF',
    categoria: 'Ejes Delantero y Trasero',
    subcategoria: 'Mazas',
    marca_repuesto: 'SKF',
    referencia_oem: '52750-1R000',
    tipo_precio: 'MOSTRAR_PRECIO',
    precio: 46900,
    stock: 14,
    condicion: 'ORIGINAL',
    compatibilidad_marca: 'Hyundai',
    compatibilidad_modelo: 'Accent',
    anio_desde: 2012,
    anio_hasta: 2022,
    motor: '1.4 / 1.6',
    descripcion: 'Cubo de rueda trasero ensamblado de 4 pernos con rodamiento sellado y sensor ABS.',
    requiere_chasis: 'NO'
  }),
  r({
    sku_proveedor: 'REP-087',
    nombre_publicado: 'Junta Homocinética Lado Rueda con Fuelle SKF',
    categoria: 'Ejes Delantero y Trasero',
    subcategoria: 'Muñones',
    marca_repuesto: 'SKF',
    referencia_oem: 'VKJA5342',
    tipo_precio: 'MOSTRAR_PRECIO',
    precio: 36500,
    stock: 16,
    condicion: 'ORIGINAL',
    compatibilidad_marca: 'Chevrolet',
    compatibilidad_modelo: 'Sail',
    anio_desde: 2011,
    anio_hasta: 2017,
    motor: '1.4',
    descripcion: 'Cabezal homocinético exterior con 22 estrías internas, grasa de litio y abrazaderas.',
    requiere_chasis: 'NO'
  }),
  r({
    sku_proveedor: 'REP-088',
    nombre_publicado: 'Polea de Alternador con Embrague Unidireccional INA / SKF',
    categoria: 'Rodamientos',
    subcategoria: 'Polea Alternador',
    marca_repuesto: 'SKF',
    referencia_oem: '535012410',
    tipo_precio: 'MOSTRAR_PRECIO',
    precio: 32900,
    stock: 18,
    condicion: 'ORIGINAL',
    compatibilidad_marca: 'Volkswagen',
    compatibilidad_modelo: 'Golf',
    anio_desde: 2014,
    anio_hasta: 2020,
    motor: '1.4 TSI / 2.0 TDI',
    descripcion: 'Polea desacopladora OAP para protección de la correa de accesorios.',
    requiere_chasis: 'NO'
  }),
  r({
    sku_proveedor: 'REP-089',
    nombre_publicado: 'Rodamiento Tensor de Correa de Accesorios SKF',
    categoria: 'Rodamientos',
    subcategoria: 'Rodamiento Tensor Distribución',
    marca_repuesto: 'SKF',
    referencia_oem: 'VKM31012',
    tipo_precio: 'MOSTRAR_PRECIO',
    precio: 21500,
    stock: 22,
    condicion: 'ORIGINAL',
    compatibilidad_marca: 'Toyota',
    compatibilidad_modelo: 'Corolla',
    anio_desde: 2014,
    anio_hasta: 2019,
    motor: '1.8',
    descripcion: 'Polea loca y rodamiento tensor de acero con pista de rodadura de precisión.',
    requiere_chasis: 'NO'
  }),
  r({
    sku_proveedor: 'REP-090',
    nombre_publicado: 'Polea Dámper de Cigüeñal con Aislador de Caucho Corteco',
    categoria: 'Rodamientos',
    subcategoria: 'Polea Cigüeñal',
    marca_repuesto: 'Corteco',
    referencia_oem: '13408-21030',
    tipo_precio: 'MOSTRAR_PRECIO',
    precio: 48900,
    stock: 9,
    condicion: 'ORIGINAL',
    compatibilidad_marca: 'Toyota',
    compatibilidad_modelo: 'Yaris',
    anio_desde: 2014,
    anio_hasta: 2020,
    motor: '1.5',
    descripcion: 'Polea amortiguadora armónica para reducción de oscilaciones torsionales del motor.',
    requiere_chasis: 'NO'
  }),
  r({
    sku_proveedor: 'REP-091',
    nombre_publicado: 'Puente Eje Trasero Completo en Acero Estampado TRW',
    categoria: 'Ejes Delantero y Trasero',
    subcategoria: 'Puente Trasero',
    marca_repuesto: 'TRW',
    referencia_oem: '55100-1R000',
    tipo_precio: 'SOLO_COTIZAR',
    precio: 340000,
    stock: 2,
    condicion: 'ORIGINAL',
    compatibilidad_marca: 'Hyundai',
    compatibilidad_modelo: 'Accent',
    anio_desde: 2012,
    anio_hasta: 2022,
    motor: '1.4 / 1.6',
    descripcion: 'Eje torsional trasero completo con soportes de bujes para suspensión.',
    requiere_chasis: 'SI'
  }),
  r({
    sku_proveedor: 'REP-092',
    nombre_publicado: 'Soporte de Motor Derecho Hidráulico Corteco',
    categoria: 'Soportes de Motor',
    subcategoria: 'Soporte de Motor',
    marca_repuesto: 'Corteco',
    referencia_oem: '12305-21220',
    tipo_precio: 'MOSTRAR_PRECIO',
    precio: 46900,
    stock: 12,
    condicion: 'ORIGINAL',
    compatibilidad_marca: 'Toyota',
    compatibilidad_modelo: 'Yaris',
    anio_desde: 2015,
    anio_hasta: 2021,
    motor: '1.5',
    descripcion: 'Pata de motor con cámara de amortiguación de fluido hidráulico anti-vibración.',
    requiere_chasis: 'NO'
  }),
  r({
    sku_proveedor: 'REP-093',
    nombre_publicado: 'Soporte Trasero de Caja de Cambios (Antipar) Corteco',
    categoria: 'Soportes de Motor',
    subcategoria: 'Soporte de Caja',
    marca_repuesto: 'Corteco',
    referencia_oem: '21930-1R000',
    tipo_precio: 'MOSTRAR_PRECIO',
    precio: 26500,
    stock: 18,
    condicion: 'ORIGINAL',
    compatibilidad_marca: 'Hyundai',
    compatibilidad_modelo: 'Accent',
    anio_desde: 2012,
    anio_hasta: 2022,
    motor: '1.4 / 1.6',
    descripcion: 'Soporte limitador de cabeceo inferior para transmisión manual y automática.',
    requiere_chasis: 'NO'
  }),
  r({
    sku_proveedor: 'REP-094',
    nombre_publicado: 'Base de Motor Izquierda Transmisión Valeo',
    categoria: 'Soportes de Motor',
    subcategoria: 'Base de Motor',
    marca_repuesto: 'Valeo',
    referencia_oem: '12372-0D110',
    tipo_precio: 'MOSTRAR_PRECIO',
    precio: 38900,
    stock: 11,
    condicion: 'ALTERNATIVO',
    compatibilidad_marca: 'Toyota',
    compatibilidad_modelo: 'Corolla',
    anio_desde: 2014,
    anio_hasta: 2019,
    motor: '1.8',
    descripcion: 'Soporte elastomérico lateral de caja de cambios con estructura de aluminio.',
    requiere_chasis: 'NO'
  }),

  // --- COMBUSTIBLE, ADMISIÓN & EGR (95-102) ---
  r({
    sku_proveedor: 'REP-095',
    nombre_publicado: 'Bomba de Bencina Sumergible Completa con Flotador Bosch',
    categoria: 'Combustible',
    subcategoria: 'Bomba de Bencina',
    marca_repuesto: 'Bosch',
    referencia_oem: '77020-0D080',
    tipo_precio: 'MOSTRAR_PRECIO',
    precio: 68900,
    stock: 14,
    condicion: 'ORIGINAL',
    compatibilidad_marca: 'Toyota',
    compatibilidad_modelo: 'Yaris',
    anio_desde: 2015,
    anio_hasta: 2021,
    motor: '1.5',
    descripcion: 'Módulo de tanque con bomba eléctrica de 3.5 bar, regulador, filtro y sensor de nivel.',
    requiere_chasis: 'NO'
  }),
  r({
    sku_proveedor: 'REP-096',
    nombre_publicado: 'Inyector de Combustible Gasolina Multipunto Denso',
    categoria: 'Combustible',
    subcategoria: 'Inyector',
    marca_repuesto: 'Denso',
    referencia_oem: '23250-21040',
    tipo_precio: 'MOSTRAR_PRECIO',
    precio: 27900,
    stock: 24,
    condicion: 'ORIGINAL',
    compatibilidad_marca: 'Toyota',
    compatibilidad_modelo: 'Yaris',
    anio_desde: 2014,
    anio_hasta: 2020,
    motor: '1.5 1NZ-FE',
    descripcion: 'Electro-inyector de 12 orificios de micro-atomización para combustión eficiente.',
    requiere_chasis: 'NO'
  }),
  r({
    sku_proveedor: 'REP-097',
    nombre_publicado: 'Bomba de Alta Presión de Petróleo Common Rail Bosch',
    categoria: 'Combustible',
    subcategoria: 'Bomba de Petróleo',
    marca_repuesto: 'Bosch',
    referencia_oem: '0445010206',
    tipo_precio: 'SOLO_COTIZAR',
    precio: 490000,
    stock: 3,
    condicion: 'ORIGINAL',
    compatibilidad_marca: 'Toyota',
    compatibilidad_modelo: 'Hilux',
    anio_desde: 2016,
    anio_hasta: 2022,
    motor: '2.4 / 2.8 D-4D',
    descripcion: 'Bomba CP4 de inyección diésel de hasta 2000 bar para sistemas common rail modernos.',
    requiere_chasis: 'SI'
  }),
  r({
    sku_proveedor: 'REP-098',
    nombre_publicado: 'Cuerpo de Aceleración Electrónico Bosch Drive-By-Wire',
    categoria: 'Admisión de Aire',
    subcategoria: 'Cuerpo Aceleración',
    marca_repuesto: 'Bosch',
    referencia_oem: '0280750535',
    tipo_precio: 'MOSTRAR_PRECIO',
    precio: 89000,
    stock: 8,
    condicion: 'ORIGINAL',
    compatibilidad_marca: 'Volkswagen',
    compatibilidad_modelo: 'Gol',
    anio_desde: 2013,
    anio_hasta: 2020,
    motor: '1.6 8V',
    descripcion: 'Mariposa motorizada de admisión con doble sensor TPS integrado de precisión.',
    requiere_chasis: 'NO'
  }),
  r({
    sku_proveedor: 'REP-099',
    nombre_publicado: 'Válvula de Control de Ralentí IAC Bosch',
    categoria: 'Admisión de Aire',
    subcategoria: 'Válvula IAC',
    marca_repuesto: 'Bosch',
    referencia_oem: '22270-21010',
    tipo_precio: 'MOSTRAR_PRECIO',
    precio: 24500,
    stock: 16,
    condicion: 'ALTERNATIVO',
    compatibilidad_marca: 'Toyota',
    compatibilidad_modelo: 'Yaris',
    anio_desde: 2008,
    anio_hasta: 2013,
    motor: '1.3 / 1.5',
    descripcion: 'Actuador paso a paso para regulación de aire en marcha mínima / ralentí.',
    requiere_chasis: 'NO'
  }),
  r({
    sku_proveedor: 'REP-100',
    nombre_publicado: 'Múltiple de Admisión con Válvulas Swirl Flap Mahle',
    categoria: 'Admisión de Aire',
    subcategoria: 'Múltiple Admisión',
    marca_repuesto: 'Mahle',
    referencia_oem: '03L129711E',
    tipo_precio: 'SOLO_COTIZAR',
    precio: 165000,
    stock: 4,
    condicion: 'ORIGINAL',
    compatibilidad_marca: 'Volkswagen',
    compatibilidad_modelo: 'Golf',
    anio_desde: 2013,
    anio_hasta: 2019,
    motor: '2.0 TDI',
    descripcion: 'Colector de admisión de poliamida reforzada con actuador de trampillas de turbulencia.',
    requiere_chasis: 'SI'
  }),
  r({
    sku_proveedor: 'REP-101',
    nombre_publicado: 'Válvula EGR Eléctrica de Recirculación de Gases Valeo',
    categoria: 'EGR',
    subcategoria: 'Válvula EGR',
    marca_repuesto: 'Valeo',
    referencia_oem: '25620-0L040',
    tipo_precio: 'MOSTRAR_PRECIO',
    precio: 115000,
    stock: 7,
    condicion: 'ORIGINAL',
    compatibilidad_marca: 'Toyota',
    compatibilidad_modelo: 'Hilux',
    anio_desde: 2015,
    anio_hasta: 2021,
    motor: '2.4 / 2.8 TDI',
    descripcion: 'Módulo de recirculación de gases de escape con sensor de retroalimentación de posición.',
    requiere_chasis: 'NO'
  }),
  r({
    sku_proveedor: 'REP-102',
    nombre_publicado: 'Enfriador Intercambiador de Gases EGR Valeo',
    categoria: 'EGR',
    subcategoria: 'Enfriador EGR',
    marca_repuesto: 'Valeo',
    referencia_oem: '25680-0L020',
    tipo_precio: 'MOSTRAR_PRECIO',
    precio: 98000,
    stock: 5,
    condicion: 'ORIGINAL',
    compatibilidad_marca: 'Toyota',
    compatibilidad_modelo: 'Hilux',
    anio_desde: 2016,
    anio_hasta: 2022,
    motor: '2.4 / 2.8 TDI',
    descripcion: 'Radiador de acero inoxidable para enfriamiento de gases EGR por agua de refrigeración.',
    requiere_chasis: 'NO'
  }),

  // --- CARROCERÍA & CERRADURAS (103-112) ---
  r({
    sku_proveedor: 'REP-103',
    nombre_publicado: 'Foco Delantero Principal Derecho con Lupa Valeo',
    categoria: 'Carrocería',
    subcategoria: 'Focos Delanteros',
    marca_repuesto: 'Valeo',
    referencia_oem: '81110-52H70',
    tipo_precio: 'MOSTRAR_PRECIO',
    precio: 89900,
    stock: 6,
    condicion: 'ORIGINAL',
    compatibilidad_marca: 'Toyota',
    compatibilidad_modelo: 'Yaris',
    anio_desde: 2017,
    anio_hasta: 2021,
    motor: '1.5',
    descripcion: 'Óptica delantera con proyector elipsoidal y luz diurna DRL integrada homologada.',
    requiere_chasis: 'NO'
  }),
  r({
    sku_proveedor: 'REP-104',
    nombre_publicado: 'Foco Trasero Izquierdo Bicolor Valeo',
    categoria: 'Carrocería',
    subcategoria: 'Focos Traseros',
    marca_repuesto: 'Valeo',
    referencia_oem: '92401-1R000',
    tipo_precio: 'MOSTRAR_PRECIO',
    precio: 49900,
    stock: 10,
    condicion: 'ORIGINAL',
    compatibilidad_marca: 'Hyundai',
    compatibilidad_modelo: 'Accent',
    anio_desde: 2012,
    anio_hasta: 2022,
    motor: '1.4 / 1.6',
    descripcion: 'Farol trasero completo con circuito impreso portalámparas y sello estanco.',
    requiere_chasis: 'NO'
  }),
  r({
    sku_proveedor: 'REP-105',
    nombre_publicado: 'Foco Neblinero Delantero con Bisel Cromado Valeo',
    categoria: 'Carrocería',
    subcategoria: 'Neblineros',
    marca_repuesto: 'Valeo',
    referencia_oem: '81210-0D042',
    tipo_precio: 'MOSTRAR_PRECIO',
    precio: 26900,
    stock: 16,
    condicion: 'ORIGINAL',
    compatibilidad_marca: 'Toyota',
    compatibilidad_modelo: 'Corolla',
    anio_desde: 2014,
    anio_hasta: 2019,
    motor: '1.8',
    descripcion: 'Faro antiniebla halógeno H11 con lente de policarbonato reforzado anti-impacto.',
    requiere_chasis: 'NO'
  }),
  r({
    sku_proveedor: 'REP-106',
    nombre_publicado: 'Espejo Retrovisor Exterior Izquierdo Eléctrico con Señalizador Valeo',
    categoria: 'Carrocería',
    subcategoria: 'Espejos',
    marca_repuesto: 'Valeo',
    referencia_oem: '87940-52E20',
    tipo_precio: 'MOSTRAR_PRECIO',
    precio: 54900,
    stock: 8,
    condicion: 'ALTERNATIVO',
    compatibilidad_marca: 'Toyota',
    compatibilidad_modelo: 'Yaris',
    anio_desde: 2016,
    anio_hasta: 2021,
    motor: '1.5',
    descripcion: 'Retrovisor lateral de 5 pines con control eléctrico y luz de viraje LED en la carcasa.',
    requiere_chasis: 'NO'
  }),
  r({
    sku_proveedor: 'REP-107',
    nombre_publicado: 'Parachoques Delantero Imprimado para Pintar',
    categoria: 'Carrocería',
    subcategoria: 'Parachoques',
    marca_repuesto: 'Valeo',
    referencia_oem: '52119-0D939',
    tipo_precio: 'MOSTRAR_PRECIO',
    precio: 72000,
    stock: 6,
    condicion: 'ALTERNATIVO',
    compatibilidad_marca: 'Toyota',
    compatibilidad_modelo: 'Yaris',
    anio_desde: 2017,
    anio_hasta: 2021,
    motor: '1.5',
    descripcion: 'Paragolpes frontal fabricado en plástico PP con base de imprimación lista para pintar.',
    requiere_chasis: 'NO'
  }),
  r({
    sku_proveedor: 'REP-108',
    nombre_publicado: 'Capot Delantero de Acero Tratado Electro-cincado',
    categoria: 'Carrocería',
    subcategoria: 'Capot',
    marca_repuesto: 'Valeo',
    referencia_oem: '53301-0D120',
    tipo_precio: 'SOLO_COTIZAR',
    precio: 125000,
    stock: 4,
    condicion: 'ALTERNATIVO',
    compatibilidad_marca: 'Toyota',
    compatibilidad_modelo: 'Yaris',
    anio_desde: 2015,
    anio_hasta: 2020,
    motor: '1.5',
    descripcion: 'Capot de motor estampado con líneas originales y protección anti-corrosión.',
    requiere_chasis: 'SI'
  }),
  r({
    sku_proveedor: 'REP-109',
    nombre_publicado: 'Guardafangos Tapabarro Delantero Izquierdo',
    categoria: 'Carrocería',
    subcategoria: 'Tapabarros',
    marca_repuesto: 'Valeo',
    referencia_oem: '53812-0D210',
    tipo_precio: 'MOSTRAR_PRECIO',
    precio: 38900,
    stock: 8,
    condicion: 'ALTERNATIVO',
    compatibilidad_marca: 'Toyota',
    compatibilidad_modelo: 'Yaris',
    anio_desde: 2016,
    anio_hasta: 2021,
    motor: '1.5',
    descripcion: 'Aleta delantera de chapa metálica de ajuste exacto para fijación de foco y parachoques.',
    requiere_chasis: 'NO'
  }),
  r({
    sku_proveedor: 'REP-110',
    nombre_publicado: 'Cerradura Eléctrica de Puerta Delantera Izquierda Valeo',
    categoria: 'Cerraduras',
    subcategoria: 'Actuadores',
    marca_repuesto: 'Valeo',
    referencia_oem: '81310-1R000',
    tipo_precio: 'MOSTRAR_PRECIO',
    precio: 34900,
    stock: 12,
    condicion: 'ORIGINAL',
    compatibilidad_marca: 'Hyundai',
    compatibilidad_modelo: 'Accent',
    anio_desde: 2012,
    anio_hasta: 2022,
    motor: '1.4 / 1.6',
    descripcion: 'Mecanismo de cierre centralizado con motor eléctrico y microswitch de puerta abierta.',
    requiere_chasis: 'NO'
  }),
  r({
    sku_proveedor: 'REP-111',
    nombre_publicado: 'Cilindro Chapa de Contacto y Encendido con Llaves Valeo',
    categoria: 'Cerraduras',
    subcategoria: 'Chapas y Cilindros',
    marca_repuesto: 'Valeo',
    referencia_oem: '81900-1W000',
    tipo_precio: 'MOSTRAR_PRECIO',
    precio: 42000,
    stock: 8,
    condicion: 'ORIGINAL',
    compatibilidad_marca: 'Kia',
    compatibilidad_modelo: 'Rio',
    anio_desde: 2014,
    anio_hasta: 2019,
    motor: '1.4',
    descripcion: 'Bombín de conmutador de arranque con 2 llaves y soporte de antena inmovilizadora.',
    requiere_chasis: 'NO'
  }),
  r({
    sku_proveedor: 'REP-112',
    nombre_publicado: 'Manilla Exterior de Puerta Delantera con Chapa Valeo',
    categoria: 'Carrocería',
    subcategoria: 'Manillas',
    marca_repuesto: 'Valeo',
    referencia_oem: '69210-0D080',
    tipo_precio: 'MOSTRAR_PRECIO',
    precio: 14500,
    stock: 22,
    condicion: 'ALTERNATIVO',
    compatibilidad_marca: 'Toyota',
    compatibilidad_modelo: 'Yaris',
    anio_desde: 2015,
    anio_hasta: 2020,
    motor: '1.5',
    descripcion: 'Tirador de puerta en plástico ABS negro texturado de alta resistencia.',
    requiere_chasis: 'NO'
  }),

  // --- EMPAQUETADURAS, ACEITES, CORREAS, PIOLAS & ACCESORIOS (113-120) ---
  r({
    sku_proveedor: 'REP-113',
    nombre_publicado: 'Empaquetadura de Culata Multilámina MLS Ajusa',
    categoria: 'Empaquetaduras y Retenes',
    subcategoria: 'Empaquetadura de Culata',
    marca_repuesto: 'Ajusa',
    referencia_oem: '10162500',
    tipo_precio: 'MOSTRAR_PRECIO',
    precio: 28900,
    stock: 18,
    condicion: 'ORIGINAL',
    compatibilidad_marca: 'Toyota',
    compatibilidad_modelo: 'Yaris',
    anio_desde: 2014,
    anio_hasta: 2021,
    motor: '1.5 1NZ-FE',
    descripcion: 'Junta de culata metálica multicapa de acero inoxidable con elastómero vitón.',
    requiere_chasis: 'NO'
  }),
  r({
    sku_proveedor: 'REP-114',
    nombre_publicado: 'Juego de Empaquetaduras de Motor Completo Ajusa',
    categoria: 'Empaquetaduras y Retenes',
    subcategoria: 'Juego de Empaquetaduras de Motor',
    marca_repuesto: 'Ajusa',
    referencia_oem: '50244100',
    tipo_precio: 'SOLO_COTIZAR',
    precio: 79900,
    stock: 6,
    condicion: 'ORIGINAL',
    compatibilidad_marca: 'Hyundai',
    compatibilidad_modelo: 'Accent',
    anio_desde: 2013,
    anio_hasta: 2022,
    motor: '1.4 / 1.6 Gamma',
    descripcion: 'Kit completo de descarbonización: culata, tapa de válvulas, retenes de válvula y múltiples.',
    requiere_chasis: 'SI'
  }),
  r({
    sku_proveedor: 'REP-115',
    nombre_publicado: 'Aceite de Motor Sintético Castrol EDGE 5W-30 LL 4L',
    categoria: 'Aceite',
    subcategoria: 'Aceite de Motor',
    marca_repuesto: 'Castrol',
    referencia_oem: 'CASTROL-5W30-4L',
    tipo_precio: 'MOSTRAR_PRECIO',
    precio: 38900,
    stock: 50,
    condicion: 'ORIGINAL',
    compatibilidad_marca: '',
    compatibilidad_modelo: '',
    anio_desde: '',
    anio_hasta: '',
    motor: '',
    descripcion: 'Lubricante sintético con tecnología Fluid TITANIUM para motores bencineros y diésel modernos.',
    requiere_chasis: 'NO'
  }),
  r({
    sku_proveedor: 'REP-116',
    nombre_publicado: 'Aceite de Transmisión Manual 75W-90 GL-4 Mobil 1L',
    categoria: 'Aceite',
    subcategoria: 'Aceite de Caja',
    marca_repuesto: 'Mobil',
    referencia_oem: 'MOBIL-75W90-1L',
    tipo_precio: 'MOSTRAR_PRECIO',
    precio: 12900,
    stock: 35,
    condicion: 'ORIGINAL',
    compatibilidad_marca: '',
    compatibilidad_modelo: '',
    anio_desde: '',
    anio_hasta: '',
    motor: '',
    descripcion: 'Fluido para cajas manuales y diferenciales con aditivos de extrema presión.',
    requiere_chasis: 'NO'
  }),
  r({
    sku_proveedor: 'REP-117',
    nombre_publicado: 'Correa de Accesorios y Alternador Gates Micro-V 6PK1195',
    categoria: 'Correas',
    subcategoria: 'Correas de Alternador',
    marca_repuesto: 'Gates',
    referencia_oem: '6PK1195',
    tipo_precio: 'MOSTRAR_PRECIO',
    precio: 14500,
    stock: 30,
    condicion: 'ORIGINAL',
    compatibilidad_marca: 'Toyota',
    compatibilidad_modelo: 'Corolla',
    anio_desde: 2015,
    anio_hasta: 2020,
    motor: '1.8 Dual VVT-i',
    descripcion: 'Correa acanalada de perfil EPDM de alta flexibilidad y resistencia al agrietamiento.',
    requiere_chasis: 'NO'
  }),
  r({
    sku_proveedor: 'REP-118',
    nombre_publicado: 'Piola Selectora de Cambios Doble con Funda Valeo',
    categoria: 'Piolas',
    subcategoria: 'Piola Selectora de Cambio',
    marca_repuesto: 'Valeo',
    referencia_oem: '33820-52310',
    tipo_precio: 'MOSTRAR_PRECIO',
    precio: 42000,
    stock: 10,
    condicion: 'ORIGINAL',
    compatibilidad_marca: 'Toyota',
    compatibilidad_modelo: 'Yaris',
    anio_desde: 2014,
    anio_hasta: 2020,
    motor: '1.5',
    descripcion: 'Par de cables de mando de caja de cambios manual con terminales de rótula rápida.',
    requiere_chasis: 'NO'
  }),
  r({
    sku_proveedor: 'REP-119',
    nombre_publicado: 'Kit de Limpieza y Cuidado de Carrocería Meguiar\'s Gold Class',
    categoria: 'Accesorios',
    subcategoria: 'Limpieza y Cuidado',
    marca_repuesto: 'Meguiar\'s',
    referencia_oem: 'G7116EU',
    tipo_precio: 'MOSTRAR_PRECIO',
    precio: 24900,
    stock: 25,
    condicion: 'ORIGINAL',
    compatibilidad_marca: '',
    compatibilidad_modelo: '',
    anio_desde: '',
    anio_hasta: '',
    motor: '',
    descripcion: 'Shampoo con acondicionadores y cera de carnauba premium de alto brillo para lavado automotriz.',
    requiere_chasis: 'NO'
  }),
  r({
    sku_proveedor: 'REP-120',
    nombre_publicado: 'Neumático Hankook Kinergy Eco2 K435 185/65 R15 88H',
    categoria: 'Accesorios',
    subcategoria: 'Neumáticos y Llantas',
    marca_repuesto: 'Hankook',
    referencia_oem: '1021482',
    tipo_precio: 'MOSTRAR_PRECIO',
    precio: 52900,
    stock: 20,
    condicion: 'ORIGINAL',
    compatibilidad_marca: 'Hyundai',
    compatibilidad_modelo: 'Accent',
    anio_desde: 2015,
    anio_hasta: 2022,
    motor: '1.4 / 1.6',
    descripcion: 'Neumático ecológico con baja resistencia al rodaje, compuesto de sílice y excelente agarre en mojado.',
    requiere_chasis: 'NO'
  })
];

// Compatibilidades adicionales para probar la hoja multi-compatibilidad
const compatibilidades = [
  { sku_proveedor: 'REP-001', compatibilidad_marca: 'Toyota', compatibilidad_modelo: 'Prius', anio_desde: 2016, anio_hasta: 2021, motor: '1.8 Hybrid' },
  { sku_proveedor: 'REP-001', compatibilidad_marca: 'Toyota', compatibilidad_modelo: 'RAV4', anio_desde: 2013, anio_hasta: 2018, motor: '2.0 / 2.5' },
  { sku_proveedor: 'REP-002', compatibilidad_marca: 'Toyota', compatibilidad_modelo: 'Prius', anio_desde: 2015, anio_hasta: 2020, motor: '1.8' },
  { sku_proveedor: 'REP-011', compatibilidad_marca: 'Toyota', compatibilidad_modelo: 'Corolla', anio_desde: 2014, anio_hasta: 2020, motor: '1.8' },
  { sku_proveedor: 'REP-011', compatibilidad_marca: 'Toyota', compatibilidad_modelo: 'RAV4', anio_desde: 2013, anio_hasta: 2018, motor: '2.0' },
  { sku_proveedor: 'REP-014', compatibilidad_marca: 'Kia', compatibilidad_modelo: 'Sportage', anio_desde: 2016, anio_hasta: 2021, motor: '2.0 CRDi' },
  { sku_proveedor: 'REP-020', compatibilidad_marca: 'Kia', compatibilidad_modelo: 'Rio', anio_desde: 2012, anio_hasta: 2018, motor: '1.4' },
  { sku_proveedor: 'REP-030', compatibilidad_marca: 'Kia', compatibilidad_modelo: 'Rio', anio_desde: 2013, anio_hasta: 2019, motor: '1.4 / 1.6' },
  { sku_proveedor: 'REP-047', compatibilidad_marca: 'Toyota', compatibilidad_modelo: 'Prado', anio_desde: 2015, anio_hasta: 2020, motor: '2.8 D-4D' },
  { sku_proveedor: 'REP-065', compatibilidad_marca: 'Toyota', compatibilidad_modelo: 'Yaris', anio_desde: 2016, anio_hasta: 2021, motor: '1.5' },
  { sku_proveedor: 'REP-066', compatibilidad_marca: 'Kia', compatibilidad_modelo: 'Rio', anio_desde: 2014, anio_hasta: 2019, motor: '1.4 / 1.6' },
  { sku_proveedor: 'REP-066', compatibilidad_marca: 'Kia', compatibilidad_modelo: 'Cerato', anio_desde: 2014, anio_hasta: 2019, motor: '1.6' },
  { sku_proveedor: 'REP-075', compatibilidad_marca: 'Toyota', compatibilidad_modelo: 'Corolla', anio_desde: 2014, anio_hasta: 2019, motor: '1.8' },
  { sku_proveedor: 'REP-085', compatibilidad_marca: 'Toyota', compatibilidad_modelo: 'Prius', anio_desde: 2016, anio_hasta: 2020, motor: '1.8 Hybrid' },
  { sku_proveedor: 'REP-113', compatibilidad_marca: 'Toyota', compatibilidad_modelo: 'Prius', anio_desde: 2015, anio_hasta: 2020, motor: '1.8' },
  { sku_proveedor: 'REP-120', compatibilidad_marca: 'Kia', compatibilidad_modelo: 'Rio', anio_desde: 2015, anio_hasta: 2021, motor: '1.4' },
  { sku_proveedor: 'REP-120', compatibilidad_marca: 'Nissan', compatibilidad_modelo: 'Versa', anio_desde: 2014, anio_hasta: 2020, motor: '1.6' }
];

// Hoja de instrucciones y versión de plantilla
const instrucciones = [
  ['PLANTILLA OFICIAL DE CARGA MASIVA DE INVENTARIO - REPUESTOP'],
  [`VERSION_PLANTILLA: ${VERSION_PLANTILLA}`],
  [''],
  ['INSTRUCCIONES DE USO:'],
  ['1. La hoja "inventario" contiene las columnas obligatorias y opcionales para la carga de productos.'],
  ['2. Columnas obligatorias: nombre_publicado, categoria, marca_repuesto, sku_proveedor, stock.'],
  ['3. tipo_precio: "MOSTRAR_PRECIO" (requiere precio numérico) o "SOLO_COTIZAR".'],
  ['4. condicion: "ORIGINAL" o "ALTERNATIVO".'],
  ['5. compatibilidad_general: "SI" o "NO" (por defecto NO). Con SI el repuesto se publica como universal y se ignoran las columnas de compatibilidad.'],
  ['6. requiere_chasis: "SI" o "NO" (por defecto NO).'],
  ['7. La hoja "compatibilidades" es opcional y permite asignar múltiples compatibilidades vehiculares por SKU.']
];

function buildWorkbook() {
  const workbook = XLSX.utils.book_new();

  // Hoja 1: inventario
  const sheetInventario = XLSX.utils.json_to_sheet(productos, { header: HEADERS });
  XLSX.utils.book_append_sheet(workbook, sheetInventario, 'inventario');

  // Hoja 2: compatibilidades
  const sheetCompat = XLSX.utils.json_to_sheet(compatibilidades, { header: COMPAT_HEADERS });
  XLSX.utils.book_append_sheet(workbook, sheetCompat, 'compatibilidades');

  // Hoja 3: instrucciones
  const sheetInstrucciones = XLSX.utils.aoa_to_sheet(instrucciones);
  XLSX.utils.book_append_sheet(workbook, sheetInstrucciones, 'instrucciones');

  return workbook;
}

const wb = buildWorkbook();
const outPath = path.join(__dirname, 'Catalogo_120_Productos_RepuesTop.xlsx');
const buffer = XLSX.write(wb, { bookType: 'xlsx', type: 'buffer' });
fs.writeFileSync(outPath, buffer);

console.log(`Excel generado con éxito: ${outPath} (${productos.length} productos, ${compatibilidades.length} multi-compatibilidades).`);
