// Catálogo de marcas de vehículo de respaldo para parsear aplicaciones en texto libre.
// Proviene de rt_marca_vehiculo ya normalizado (Fase 5 del plan de auditoría de carga, 29-09-2026):
// 261 marcas, un solo nombre por marca. Se regenera desde
// GET /api/v1/catalogos/inventario/marcas-vehiculo; los alias del padrón ("KIA MOTORS") están en
// nombresCatalogoVehiculo.ts.
export const MARCAS_VEHICULO_BASE: string[] = [
    "Acadian",
    "Acura",
    "Aima",
    "Alfa Romeo",
    "American Motors",
    "Aprilia",
    "ARO",
    "Asia Motors",
    "Aston Martin",
    "Audi",
    "Austin",
    "Autorrad",
    "BAIC",
    "Bajaj",
    "Bashan",
    "Beiging",
    "Benda",
    "Benelli",
    "Bentley",
    "Benyi",
    "Benzhou",
    "Bigfoot",
    "Bimota",
    "BMW",
    "Boatian",
    "Brilliance",
    "BRP CAN AM",
    "Buell",
    "Buick",
    "Bultaco",
    "BYD",
    "Cadillac",
    "Cagiva",
    "Caterham",
    "CF Moto",
    "Changan",
    "Changhe",
    "Chery",
    "Chevrolet",
    "Chrysler",
    "Citroen",
    "Commer",
    "Corsa",
    "Cupra",
    "Cyclone",
    "Dacia",
    "Daelim",
    "Daewoo",
    "Dagger",
    "Daihatsu",
    "Datsun",
    "Dayun",
    "DFSK",
    "Dodge",
    "Dongfeng",
    "DS Automobiles",
    "Ducati",
    "Dunna",
    "Dyna",
    "E-Takasaki",
    "Euromot",
    "Exeed",
    "F.S.O.",
    "Farizon",
    "FAW",
    "Ferrari",
    "Fiat",
    "Flstf",
    "Ford",
    "Foton",
    "FOX",
    "FXA",
    "G.M.C.",
    "GAC",
    "GAC Gonow",
    "Garelli",
    "Gasgas",
    "GDM",
    "Gecko",
    "Geely",
    "Gilera",
    "Great Wall",
    "Guzzi",
    "Hafei",
    "Haima",
    "HAO JUE",
    "Harley-Davidson",
    "Hartford",
    "Haval",
    "Hensim",
    "Hero-Puch",
    "Hillman",
    "Honda",
    "Husaberg",
    "Husqvarna",
    "Hyosung",
    "Hyundai",
    "Indian",
    "Infiniti",
    "International",
    "Isuzu",
    "Italjet",
    "Iveco",
    "JAC",
    "Jaecoo",
    "Jaguar",
    "Jawa",
    "Jeep",
    "Jetour",
    "Jianshe",
    "JIM",
    "Jinbei",
    "JMC",
    "Kaiyi",
    "Karma",
    "Karry",
    "Kawasaki",
    "Kayak",
    "Keeway",
    "Kenbo",
    "Kia",
    "Kinlon",
    "Koenigsegg",
    "Kove",
    "KTM",
    "KYC",
    "Kymco",
    "Lada",
    "Lamborghini",
    "Lambretta",
    "Lancia",
    "Land Rover",
    "Landwind",
    "Leapmotor",
    "Lexus",
    "Lifan",
    "Lincoln",
    "Linhai",
    "Livan",
    "LML",
    "Loncin",
    "Lotus",
    "Luojia",
    "Lynk CO",
    "Mahindra",
    "Maico",
    "Maple",
    "Maserati",
    "Maxus",
    "Mazda",
    "McLaren",
    "Mercedes-Benz",
    "Mercury",
    "MG",
    "Mini",
    "Mitsubishi",
    "Montelli",
    "Montesa",
    "Morgan",
    "Morini",
    "Morris",
    "Moto Becane",
    "Motomel",
    "Motorrad",
    "Motrac",
    "MSK",
    "MV Agusta",
    "Nammi",
    "Neta",
    "Nissan",
    "NSU",
    "Odes",
    "Oldsmobile",
    "Omoda",
    "Opel",
    "Ora",
    "Ossa",
    "Palla",
    "Peugeot",
    "PGO",
    "Piaggio",
    "Pionner",
    "Plymouth",
    "Polaris",
    "Polski Fiat",
    "Pontiac",
    "Porsche",
    "Proton",
    "Puma",
    "Qjmotor",
    "RAM",
    "RBS",
    "Regal Raptor",
    "Renault",
    "Riddara",
    "Rizato",
    "Rolls Royce",
    "Rover",
    "Royal Enfield",
    "Saab",
    "Sachs",
    "Saehan",
    "Samsung",
    "Sanfu",
    "Sanlg",
    "Sanya",
    "Seat",
    "Segway",
    "SG",
    "Shineray",
    "Simca",
    "Skoda",
    "Skygo",
    "SMA",
    "Smart",
    "Soueast",
    "Speed UP",
    "Spitz",
    "SsangYong",
    "Subaru",
    "Super Soco",
    "Suzuki",
    "SWM",
    "SYM",
    "Takasaki",
    "Tank",
    "Tata",
    "Tesla",
    "TM",
    "Torito",
    "Toyota",
    "Triumph",
    "TVS",
    "UAZ",
    "United Motors",
    "Ural",
    "Verona",
    "Vespa",
    "Voge",
    "Volkswagen",
    "Voltera",
    "Volvo",
    "Wangye",
    "Willys",
    "Wolken",
    "Xgjao",
    "Xingyue",
    "Xmotors",
    "Yamaha",
    "Yamamoto",
    "Yinxiang",
    "Yugo",
    "Zanellas",
    "Zastava",
    "ZNA",
    "Znen Group",
    "Zongshen",
    "Zontes",
    "Zotye",
    "Zundapp",
    "ZX Auto",
];
