// Catálogo de marcas de vehículo de respaldo para parsear aplicaciones en texto libre.
// Proviene de rt_marca_vehiculo (265 marcas oficiales de RepuesTop).
export const MARCAS_VEHICULO_BASE: string[] = [
    "ACADIAN",
    "ACURA",
    "AIMA",
    "ALFA ROMEO",
    "AMERICAN MOTORS",
    "APRILIA",
    "ARO",
    "ASIA MOTORS",
    "ASTON MARTIN",
    "AUDI",
    "AUSTIN",
    "AUTORRAD",
    "BAIC",
    "BAJAJ",
    "BASHAN",
    "BEIGING",
    "BENDA",
    "BENELLI",
    "BENTLEY",
    "BENYI",
    "BENZHOU",
    "BIGFOOT",
    "BIMOTA",
    "BMW",
    "BOATIAN",
    "Brilliance",
    "BRP CAN AM",
    "BUELL",
    "BUICK",
    "BULTACO",
    "BYD",
    "CADILLAC",
    "CAGIVA",
    "CATERHAM",
    "CF MOTO",
    "CFMOTO",
    "Changan",
    "CHANGHE",
    "Chery",
    "Chevrolet",
    "CHRYSLER",
    "CITROEN",
    "COMMER",
    "CORSA",
    "CUPRA",
    "CYCLONE",
    "DACIA",
    "DAELIM",
    "DAEWOO",
    "DAGGER",
    "DAIHATSU",
    "DATSUN",
    "DAYUN",
    "DFSK",
    "DODGE",
    "Dongfeng",
    "DS AUTOMOBILES",
    "DUCATI",
    "DUNNA",
    "DYNA",
    "E-TAKASAKI",
    "EUROMOT",
    "Exeed",
    "F.S.O.",
    "FARIZON",
    "FAW",
    "FERRARI",
    "FIAT",
    "FLSTF",
    "Ford",
    "Foton",
    "FOX",
    "FXA",
    "G.M.C.",
    "GAC",
    "GAC GONOW",
    "GARELLI",
    "GASGAS",
    "GDM",
    "GECKO",
    "Geely",
    "GILERA",
    "Great Wall",
    "GUZZI",
    "Hafei",
    "HAIMA",
    "HAO JUE",
    "HARLEY-DAVIDSON",
    "HARTFORD",
    "Haval",
    "HENSIM",
    "HERO-PUCH",
    "HILLMAN",
    "Honda",
    "HUSABERG",
    "HUSQVARNA",
    "HYOSUNG",
    "Hyundai",
    "INDIAN",
    "INFINITI",
    "INTERNATIONAL",
    "ISUZU",
    "ITALJET",
    "IVECO",
    "JAC",
    "Jaecoo",
    "JAGUAR",
    "JAWA",
    "JEEP",
    "Jetour",
    "JIANSHE",
    "JIM",
    "JINBEI",
    "JMC",
    "Kaiyi",
    "KARMA",
    "KARRY",
    "KAWASAKI",
    "KAYAK",
    "KEEWAY",
    "KENBO",
    "Kia",
    "KIA MOTORS",
    "KINLON",
    "KOENIGSEGG",
    "KOVE",
    "KTM",
    "KYC",
    "KYMCO",
    "LADA",
    "LAMBORGHINI",
    "LAMBRETTA",
    "LANCIA",
    "LAND ROVER",
    "LANDWIND",
    "LEAPMOTOR",
    "LEXUS",
    "Lifan",
    "LINCOLN",
    "LINHAI",
    "LIVAN",
    "LML",
    "LONCIN",
    "LOTUS",
    "LUOJIA",
    "LYNK CO",
    "MAHINDRA",
    "MAICO",
    "MAPLE",
    "MASERATI",
    "Maxus",
    "Mazda",
    "MCLAREN",
    "Mercedes-Benz",
    "MERCEDES BENZ",
    "MERCURY",
    "MG",
    "MINI",
    "Mitsubishi",
    "MONTELLI",
    "MONTESA",
    "MORGAN",
    "MORINI",
    "MORRIS",
    "MOTO BECANE",
    "MOTOMEL",
    "MOTORRAD",
    "MOTRAC",
    "MSK",
    "MV AGUSTA",
    "NAMMI",
    "NETA",
    "Nissan",
    "NSU",
    "ODES",
    "OLDSMOBILE",
    "Omoda",
    "Opel",
    "Ora",
    "OSSA",
    "PALLA",
    "PEUGEOT",
    "PGO",
    "PIAGGIO",
    "PIONNER",
    "PLYMOUTH",
    "POLARIS",
    "POLSKI FIAT",
    "PONTIAC",
    "PORSCHE",
    "PROTON",
    "PUMA",
    "QJMOTOR",
    "RAM",
    "RBS",
    "REGAL RAPTOR",
    "Renault",
    "RIDDARA",
    "RIZATO",
    "ROLLS ROYCE",
    "ROVER",
    "ROYAL ENFIELD",
    "SAAB",
    "SACHS",
    "SAEHAN",
    "SAMSUNG",
    "SANFU",
    "SANLG",
    "SANYA",
    "SANYANG SYM",
    "SEAT",
    "SEGWAY",
    "SG",
    "SHINERAY",
    "SIMCA",
    "SKODA",
    "SKYGO",
    "SMA",
    "SMART",
    "Soueast",
    "SPEED UP",
    "SPITZ",
    "SsangYong",
    "SUBARU",
    "SUPER SOCO",
    "Suzuki",
    "SWM",
    "SYM",
    "TAKASAKI",
    "Tank",
    "TATA",
    "TESLA",
    "TM",
    "TORITO",
    "Toyota",
    "TRIUMPH",
    "TVS",
    "UAZ",
    "UNITED MOTORS",
    "URAL",
    "VERONA",
    "VESPA",
    "VOGE",
    "Volkswagen",
    "VOLTERA",
    "VOLVO",
    "WANGYE",
    "WILLYS",
    "WOLKEN",
    "XGJAO",
    "XINGYUE",
    "XMOTORS",
    "YAMAHA",
    "YAMAMOTO",
    "YINXIANG",
    "YUGO",
    "ZANELLAS",
    "ZASTAVA",
    "ZNA",
    "ZNEN GROUP",
    "ZONGSHEN",
    "ZONTES",
    "Zotye",
    "ZUNDAPP",
    "ZX AUTO"
];
